// Module included in the following assemblies:
//
// assembly-introduction-cost-management.adoc
:_module-type: CONCEPT
:experimental:

[id="about-cost-management_{context}"]
= About cost management

[role="_abstract"]
Cost management is an OpenShift Container Platform service that enables you to better understand and track costs for clouds and containers. It is based on the upstream project Koku.

You can access the cost management application from https://cloud.redhat.com/cost-management/.

Cost management allows you to simplify management of resources and costs across various environments, including:

* Container platforms such as OpenShift Container Platform
* Public clouds such as Amazon Web Services (AWS) and Microsoft Azure


The cost management application allows you to:

* Visualize, understand and analyze the use of resources and costs
* Forecast your future consumption and compare them with budgets
* Optimize resources and consumption
* Identify patterns of usage that should be investigated
* Integrate with third party tools that can benefit from cost and resourcing data



== Terminology

Source::
A cloud provider account that is connected to cost management to be monitored, for example, an OpenShift Container Platform deployment, or an AWS or Azure account.

Organization Administrator::

The highest permission level for Red Hat accounts, with full access to content and features. This is the only role that can manage users and control their access and permissions on an account. An account may have multiple Organization Administrators.

See https://access.redhat.com/articles/1757953[Roles and Permissions for Red Hat Subscription Management] for more details.
