// Module included in the following assemblies:
//
// assembly-introduction-cost-management.adoc
:_module-type: CONCEPT
:experimental:

[id="about-cost-management_{context}"]
= About {product-title}

[role="_abstract"]
Cost management is an OpenShift Container Platform service that enables you to better understand and track costs for clouds and containers. It is based on the upstream project Koku.

You can access the {product-title} application from {link-cost-management}.

Cost management allows you to simplify management of resources and costs across various environments, including:

* Container platforms such as OpenShift Container Platform
* Public clouds such as Amazon Web Services (AWS), Google Cloud, and Microsoft Azure


The {product-title} application allows you to:

* Visualize, understand and analyze the use of resources and costs
* Forecast your future consumption and compare them with budgets
* Optimize resources and consumption
* Identify patterns of usage that should be investigated
* Integrate with third party tools that can benefit from cost and resourcing data

