// Module included in the following assemblies:
//
// assembly_configuring_tags_sources.adoc

// Base the file name and the ID on the module title. For example:
// * file name: adding_tags_to_an_Azure_resource.adoc
// * ID: [id="adding_tags_to_an_Azure_resource"]
// * Title: = Adding tags to an Azure resource

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="adding_tags_to_an_Azure_resource{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Adding tags to an Azure resource

Adding an Azure source creates identifiers for virtual machine instances automatically, which cost management uses similarly to a tag to associate Azure resources to related OpenShift resources.

You can also add your own tags in Azure at the individual resource level. 

Create and apply Azure tags for cost management using the following instructions in the Azure documentation: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources[_Use tags to organize your Azure resources and management hierarchy_].

