// Module included in the following assemblies:
//
// assembly-configuring-tags-sources.adoc
:_module-type: PROCEDURE
:experimental:


[id="adding-tags-to-an-AWS-resource_{context}"]
= Adding tags to an AWS resource

[role="_abstract"]
Amazon creates certain identifiers automatically, like the EC2 instance resource identifier (a number such as `i-123456789`), which {product-title} uses similarly to a tag.

You can also add your own tags at the individual resource level. These tags must be activated for Cost and Usage Reporting to export them to the {product-title} application.

Configure AWS tags for {product-title} using the following steps:

.Procedure

. Create and apply tags to your AWS resources.
+
See link:https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/custom-tags.html[_User-Defined Cost Allocation Tags_] in the AWS documentation for instructions.
+
. Activate the tags you want to be collected by the {product-title} application via the Cost and Usage Report. In the AWS Billing console, select the tags you want to activate from the Cost Allocation Tags area.
+
See link:https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activate-built-in-tags.html[_Activating the AWS-Generated Cost Allocation Tags_] in the AWS documentation for instructions.
