// Module included in the following assemblies:
//
// assembly-configuring-tags-sources.adoc
:_module-type: PROCEDURE
:experimental:

[id="adding-tags-to-an-OCP-resource_{context}"]
= Viewing labels in an OpenShift namespace

[role="_abstract"]
The AWS or Azure tag equivalent in OpenShift is a label, which also consists of a key:value pair. Cost management collects OpenShift tag data from nodes, pods, and persistent volumes (or persistent volume claims) using Prometheus metrics and Operator Metering.

// COST-571, only the collected tags are available. User cannot add more tags/labels. We do not want users adding tags using the OCP templates, which is why we struck that information. For the future, we are planning on supporting the namespace labels (part being removed) once the operator rework is done. So come next January we will likely be adding this section back.
//Module title changed to "Viewing" because users cannot add. Change back to "Adding" when that capability is restored.

////
One method of adding tags to OpenShift resources is to specify labels to add in a template. See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/images/using-templates[Using templates] in the OpenShift Container Platform documentation.

Or to add labels manually:

.Procedure

To add a label to a namespace in OpenShift:

. In the OpenShift web console, navigate to *Administration > Namespaces*.
. Click your Namespace to open the Namespace overview.
. From the Namespace Overview page, click *Actions > Edit labels* to open the dialog box showing labels assigned to your project.
. Enter your labels, for example: `openshift.io/cluster-monitoring=true`
. Click Save.
. Run the Usage Collector script again to refresh the tags:
+
----
/path/to/ocp_usage.sh –collect
----

Wait an hour for the data to refresh and be visible in cost management.

////

//.Verification steps

To view the available tags, navigate to a resource in the OpenShift web console. Any assigned labels are listed under the *Labels* heading, for example: _openshift.io/cluster-monitoring=true_.

////
.Additional resources

For more information about creating OpenShift labels, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html-single/nodes/index#nodes-nodes-working-updating_nodes-nodes-working[Nodes] in the OpenShift Container Platform documentation.
////
