// Module included in the following assemblies:
//
// assembly_organizing_cost_data_using_tags.adoc

// Base the file name and the ID on the module title. For example:
// * file name: adding_tags_to_an_AWS_resource.adoc
// * ID: [id="adding_tags_to_an_AWS_resource"]
// * Title: = Adding tags to an AWS resource

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="doing-one-procedure_{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Adding tags to an AWS resource

Amazon creates certain identifiers automatically, like the EC2 instance resource identifier (a number such as `i-123456789`), which cost management uses similarly to a tag.

You can also add your own tags at the individual resource level. These tags must be activated for Cost and Usage reporting to export them to the cost management application.

Configure AWS tags for cost management using the following steps:

.Procedure

. Create and apply tags to your AWS resources. 
+
See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/custom-tags.html[_User-Defined Cost Allocation Tags_] in the AWS documentation for instructions.
+
. Activate the tags you want to be collected by the cost management application via the Cost and Usage Report. In the AWS Billing console, select the tags you want to activate from the Cost Allocation Tags area. 
+
See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activate-built-in-tags.html[_Activating the AWS-Generated Cost Allocation Tags_] in the AWS documentation for instructions.

