// Module included in the following assemblies:
//
// assembly-adding-openshift-container-platform-source.adoc
:_module-type: PROCEDURE
:experimental:

[id="basic-authentication_{context}"]
= Configuring basic authentication for cost operator

[role="_abstract"]
You can configure the cost operator to use basic authentication. By default, the cost operator uses token authentication.

There are two procedures required when you configure basic authentication.

* xref:creating-secret-pair[Creating the secret key/value pair for basic authentication]
* xref:modify-yaml-file[Modifying the YAML file]

[id="creating-secret-pair"]
[[creating-secret-pair]]
== Creating the secret key/value pair for basic authentication

.Prerequisites
* You are logged into the {openshift} web console with cluster administrator privileges.
* The *{operator-formal}* appears in the *Installed Operators* tab.
* You have a username and password for your {platform-title} account.


.Procedure
This procedure describes setting up basic authentication using the {openshift} web console.

. In the {openshift} web console, click on the *Workloads > Secrets* tab.
. In the *Secrets* window, select *Project:{operator}* from the dropdown.
. Click the *Create > Key/Value Secret* selection.
. In the *Create Key/Value Secret* window enter the following information to create a new secret that contains a username key and a password key and a value for each key.
.. Enter a name for your secret in the *Secret Name* field.
+
[source,yaml]
----
basic-auth-secret
----
.. In the *Key* field, enter `username`.
+
[source,yaml]
----
username
----
.. In the *Value* field for the key `username`, enter the actual username for your authorized {platform-title} user account.
+
.Value for username key
[source,yaml,subs="+quotes"]
----
_your_red_hat_username_
----
.. Click the `Add Key/Value` link to add the required password key name and value.
.. In the *Key* field, enter `password`. 
+
[source,yaml]
----
password
----
.. In the *Value* field for the key `password`, enter the actual password for your authorized {platform-title} user account.
+
.Value for password key
[source,yaml,subs="+quotes"]
----
_your_red_hat_password_
----
.. Click the *Create* button to complete the creation of your basic authorization secret.
.. After you click the *Create* button, you can verify the key/value details for the secret.
+
NOTE: Do _not_ add the secret to the workload.

[id="modify-yaml-file"]
[[modify-yaml-file]]
== Modifying the YAML file

Modify the {operator-formal} API YAML file to use basic authentication with a secret username and password key/value pair.


.Prerequisites
* You are logged into the {openshift} web console with cluster administrator privileges.
* You created a secret name for the username and password key/value pair.
* The {operator-formal} is installed.

.Procedure

. Click on the *Operators > Installed Operators* tab.
. Locate the row that contains *{operator-formal}* and click on the *{operator-formal}* link that is under the *Provided APIs* heading.
. When the *{operator-config}* window appears, click on the configuration file listed in the *Name* column.
+
The default name is +{sample-file}+.
. When the +{sample-file}+ window appears, click in the *YAML* tab to open an edit and view window.
. Locate the following lines in the YAML view.
+
[source,yaml]
----
  authentication:
    type: token
----
. Change `type: token` to `type: basic`.
. Insert a new line for `secret_name`. Enter the value for  `secret_name`, which is the name you previously created.
+
.Example
[source,yaml]
----
  authentication:
    secret_name: basic-auth-secret
    type: basic
----
. Click the *Save* button. A confirmation message appears.
