// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: con_how_cost_associates_tags.adoc
// * ID: [id="con_how_cost_associates_tags"]
// * Title: = How cost management associates tags

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="con_how_cost_associates_tags"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
You must configure tags in each source before cost management can use the tags to automatically organize your cost data. 

After adding your sources to cost management:

. Tag or label resources on each of your sources. See xref:assembly_configuring_tags_sources[].
. Enable OpenShift tag grouping to further organize your cost data views for each source. See xref:enabling_tag_grouping_OCP[].
. Refine and add to your tags to optimize your view of cost data. See xref:con_planning_tagging_strategy[].

[NOTE]
====
See the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html-single/getting_started_with_cost_management/index[_Getting started with cost management_] guide for instructions on configuring sources.
====



= How cost management associates tags



AWS tags and OpenShift labels both consist of key:value pairs. When the key:value pairs match, the AWS and OpenShift costs are automatically associated by cost management. Note that tag matching is not case sensitive: for example, an AWS resource AWS tagged _APP_ and an OpenShift resource tagged _app_ are a match:


.Example: Tag matching
[options="header"]
|====
|Source and resource type|Key|Value
|AWS Resource (RDS)|APP|Cost-Management
|OpenShift pod|app|cost-management
|====


If an AWS resource tag matches with multiple OpenShift projects, the cost and usage of that resource are split evenly between the matched projects. 

Note that this is not the case with AWS compute resources that are matched via the instance ID-node relationship. In that case, cost and usage are broken down using information about a project’s resource consumption within the OpenShift cluster.

By default, cost management tracks AWS compute usage and costs by associating the Amazon EC2 instance ID with the OpenShift Container Platform node running on that instance. 


== Tag matching hierarchy in cost management

To identify your OpenShift resources running on AWS or Azure instances, cost management matches tags between sources in the following order:

. Direct resource matching (EC2 instance ID)
. Special OpenShift tags
. Custom tags


=== Direct resource matching (EC2 instance ID)

The sources apply these tags automatically. This form of tagging provides a direct link between AWS EC2 instances and OpenShift nodes.

AWS assigns every EC2 instance a resource identifier (a number such as `i-01f44b3d90ef90055`). OpenShift nodes are matched directly to the AWS EC2 instance the cluster is running on using the AWS resource identifier. The OpenShift reports in cost management (generated from Prometheus data) include this identifier for nodes.

//.Example - screenshot?

=== Special OpenShift tags

There are three special-case AWS tags you can use to associate cost with OpenShift:

* `openshift_cluster`
* `openshift_node`
* `openshift_project`

These tags have matching priority over custom tags, and are especially useful in differentiating the costs of different OpenShift clusters running on the same AWS instance.

To use this tagging method to identify an OpenShift cluster:

. Name your OpenShift cluster (in this example, dev-cluster).
. Tag your AWS instance with the key `openshift_cluster`, and provide the cluster name as the value (in this example, `dev-cluster`).


.Example: Special OpenShift tags
[options="header"]
|====
|Source and resource type|Key|Value
|AWS Resource (RDS)|`openshift_cluster`|`dev-cluster`
|OpenShift cluster|
No tags needed. Name your OpenShift cluster `dev-cluster`.

|No tags needed. Name your OpenShift cluster `dev-cluster`.
|====


=== Custom tags

You can use any key:value combination as tags, and cost management will associate identical tag key and values together. You can then group costs by tag key, account, service, region, and more to view your costs and charge for that tag.

.Example: Custom tags
[options="header"]
|====
|Source and resource type|Key|Value
|AWS Resource (RDS)|`team`|`engineering`
|OpenShift pod|`team`|`engineering`
|====



//.Additional resources


