// Module included in the following assemblies:
//
// assembly_introduction_cost_management.adoc

// Base the file name and the ID on the module title. For example:
// * file name: con_about_cost_management.adoc
// * ID: [id="con_about_cost_management"]
// * Title: = About cost management

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="con_about_cost_management"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= About cost management
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.
  
Cost management is an OpenShift Container Platform service that enables you to better understand and track costs for clouds and containers. It is based on the upstream project Koku.

Cost management allows you to simplify management of resources and costs across various environments, including:

* Public clouds  - such as Amazon Web Services (AWS), Microsoft Azure, Google Compute Engine, IBM Cloud
* Private clouds - such as Red Hat OpenStack Platform
* Virtualized environments  - such as Red Hat Virtualization (RHV), VMware
* Container platforms  - such as OpenShift Container Platform
* Bare metal servers


The cost management application allows you to:

* Visualize, understand and analyze the use of resources and costs
* Forecast your future consumption and compare them with budgets
* Optimize resources and consumption
* Identify patterns of usage that should be investigated
* Integrate with third party tools that can benefit from cost and resourcing data



== Terminology

Source::
A cloud provider account that is connected to cost management to be monitored, for example, an AWS or Azure account, or an OpenShift Container Platform deployment.

Organization Administrator:: 

The highest permission level for Red Hat accounts, with full access to content and features. This is the only role that can manage users and control their access and permissions on an account. An account may have multiple Organization Administrators.

See https://access.redhat.com/articles/1757953[Roles and Permissions for Red Hat Subscription Management] for more details.



