// Module included in the following assemblies:
//
// assembly_introduction_cost_management.adoc

// Base the file name and the ID on the module title. For example:
// * file name: con_planning_cost_management.adoc
// * ID: [id="con_planning_cost_management"]
// * Title: = Planning for cost management

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="con_planning_cost_management"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Planning for cost management

When configuring cost management for your needs, consider the scope of your environments that you want to manage costs for, and the users who will have access to the data.

Some considerations in creating a new Red Hat organization and users for different customer types include:

*Scope:*

* Customer company wide
* Customer division or organization wide
* Partner company managing several tenants

*Data:*

* How does your business need the data? Do you want information about projects, or users, for example?
* Planning AWS tags to reflect previous use cases.
* Enforcement: Is there any way for you to ensure that the proper tags and metadata are included in each item of the inventory?
	
// Should this part be moved to the RBAC section?
Determine the required level of access for your users based on the following predefined roles in cost management:

* Cost Administrator:  grants read and write permissions
* Cost Cloud Viewer:  grants read permissions on cost reports related to cloud sources
* Cost OpenShift Viewer:  grants read permissions on cost reports related to OpenShift sources
* Cost Price List Administrator:  grants read and write permissions on price list rates
* Organization Administrator: a Red Hat account user who can manage users and control their access and permissions




