// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: con_export_API_how_it_works.adoc
// * ID: [id="con_export_API_how_it_works"]
// * Title: = How the data export API works

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="concept-explanation_{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= How the data export API works

The API exports cost data from Koku's database originating from your sources. 

The export generally includes results from Koku's "daily" and "daily summary" database tables and are generally bound by specific requested dates. Exported files are separated by Koku account, source/provider, date, and table name. 

// generally? is there an occasion when they don't include these results and are bound by the dates?

//exporting files are separated by, or the data in files is separated by...?

Koku writes these files in CSV format to the AWS S3 bucket specified in the request.

////
Upon initial request:

* Koku returns a synchronous response to indicate that it has started the process, but the remainder of the operations are asynchronous. You must check back at the API if you want to see the current state of your data export request.
* Koku checks for any in-progress requests with the same date parameters as that request. If Koku is already working on an export (status is pending or processing) with the same dates, the new request is rejected with a 400 error and a message indicating as such ('A pending or processing data export already exists with the given "start_date" and "end_date".'). If either an export with the same dates does not exist or does exist with a terminal state, Koku allows the request to be created.
////

//== Limitations

// How far back can a user search? Is there a limit to what Koku will store?

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

////