// Module included in the following assemblies:
//
// assembly_using_cost_models.adoc

// Base the file name and the ID on the module title. For example:
// * file name: con_what_is_a_cost_model.adoc
// * ID: [id="con_what_is_a_cost_model"]
// * Title: = What is a cost model?

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="con_what_is_a_cost_model"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= What is a cost model?
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.

It can be difficult to find out the real cost of the cloud. Different sources provide a variety of cost
data and metrics, which can be complicated to calculate together and accurately distribute the costs.

A cost model is a framework used to define the calculations for the costs stored in cost management. Using a cost model, you can associate a price to metrics provided by your
sources to charge for utilization of resources. 

In some cases, those costs are related to the raw costs
of the infrastructure, while others will be based on a price list that associates usage to charges. The
data must be normalized before you can add a markup to it to cover your overhead,
and then distribute the charges to your resources and/or end customers.

Being able to charge based on usage is a key requirement for chargeback and showback, as it
provides the ability to set up a price by usage. It helps to align costs to utilization: those customers
that use a resource more will be charged more.





