////

////
:_content-type: PROCEDURE

[id="configuring-aws-savings-plans_{context}"]
= Configuring AWS billing plans

[role="_abstract"]
By default, {product-title} calculates AWS cost according to your usage cost for that date. If you have a special billing arrangement with AWS such as amortized billing or blended rates, you can configure these calculations from the {link-cost-settings} page. This allows your cost reports to more accurately reflect your AWS billing.

For more information on AWS billing, see link:https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/con-bill-blended-rates.html[_Understanding Consolidated Bills_] in the AWS documentation. 


Cost management supports three cost calculation options to accommodate AWS billing plans: 

Unblended (Default):: Your costs are calculated according to your usage cost for that date. 
Amortized:: Your recurring and upfront costs will be distributed evenly throughout the billing period. 
Blended:: Your costs are calculated according to AWS blended rates.

This procedure describes how to set your cost calculation to *Amortized* or *Blended* from the default *Unblended*. 

.Prerequisites

* AWS source added to {product-title}.
* Access to {platform-title} as an Organization Administrator.

.Procedure

. From {platform-title}, navigate to the {link-cost-settings} page.
. Under *Show cost as* select *Amortized* or *Blended*.
. Click *Save*.
