// Module included in the following assemblies:
// assembly_adding_azure_sources.adoc
[id="configuring_azure_roles"]
[[configuring_azure_roles]]
== Configuring Azure roles

Red Hat recommends configuring dedicated credentials to grant cost management read-only access to Azure cost data.  Configure a Storage Account Contributor and Reader role in Azure to provide this access to cost management.

. In Azure Cloud Shell, run the following command to obtain your Subscription ID: 
+
----
$ az account show --query "{subscription_id: id }"
----
+
. In the cloud.redhat.com *Sources* wizard, enter your *Subscription ID*. Click *Next* to move to the next screen.
. In Azure Cloud Shell, run the following command to create a Cost Management Storage Account Contributor role, and obtain your tenant ID, client (application) ID, and client secret: 
+
----
$ az ad sp create-for-rbac -n "CostManagement" --role "Storage Account Contributor" --query '{"tenant": tenant, "client_id": appId, "secret": password}'
----
+
. In the cloud.redhat.com *Sources* wizard, enter your Azure *Tenant ID*, *Client ID*, and *Client Secret*.
. In Azure Cloud Shell, run the following command to create a Cost Management Reader role with your subscription ID. Copy the full command from the cloud.redhat.com *Sources* wizard, which will automatically substitute your Azure subscription ID obtained earlier for _<SubscriptionID>_: 
+
----
$ az role assignment create --role "Cost Management Reader" --assignee http://CostManagement --subscription <SubscriptionID>
----
+
. Click *Next*.
