// Module included in the following assemblies:
// assembly_adding_ocp_sources.adoc
[id="configuring_cost_mgmt-operator"]
[[configuring_cost_mgmt-operator]]
== Configuring the Cost Management Operator

The Cost Management Operator (`cost-mgmt-operator`) collects the metrics required for cost management.    

After installing the Cost Management Operator, configure authentication and the `operator-metering` namespace, then configure the Cost Management Operator.

.Prerequisites

* OpenShift Container Platform 4.3 or newer
* The Cost Management Operator installed in the `operator-metering` namespace
* A user with access to the `openshift-config` namespace

.Procedure

. Configure authentication inside the `openshift-metering` project. This allows you to upload OpenShift data to cloud.redhat.com. 
+
[NOTE]
====
You can use token authentication or basic authentication to upload the usage reports (metrics) to cost management. The default and recommended method is token authentication.
====
+
.. Copy the following into a file called `auth_secret.yaml`:
+
----
kind: Secret
apiVersion: v1
metadata:
  name: auth-secret-name
  namespace: openshift-metering
  annotations:
    kubernetes.io/service-account.name: cost-mgmt-operator
data:
  username: >-
    Y2xvdWQucmVkaGF0LmNvbSB1c2VybmFtZQ==
  password: >-
    Y2xvdWQucmVkaGF0LmNvbSBwYXNzd29yZA==
  token: >-
    Y2xvdWQucmVkaGF0LmNvbSB0b2tlbg==
----
+
.. Choose a name for your authentication secret and replace the `metadata.name` value with it.
.. To configure token authentication (the default method), obtain the correct _auth_ token and then edit the secret to replace the token value:
+
... Install the https://stedolan.github.io/jq/download/[`jq`] JSON processor.
... Change to the `openshift-config` namespace:
+
----
$ oc project openshift-config
----
+
... Replace the token value in `auth_secret.yaml` with the authentication token for _cloud.openshift.com_. Obtain the token by running the following command, and copy only the "_tokenvalue_" to `auth_secret.yaml` (excluding the quotation marks):
+
----
$ oc get secret pull-secret -o "jsonpath={.data.\.dockerconfigjson}" | base64 --decode | jq '.auths."cloud.openshift.com".auth'
----
+
[NOTE]
====
To use basic authentication, edit the secret to replace the username and password values with your base64-encoded username and password for connecting to cloud.redhat.com.
====
+
.. Deploy the secret to your OpenShift cluster in the `openshift-metering` namespace:
+
----
$ oc create -f auth-secret.yaml
----
+
For both methods of authentication, the name of the secret should match the _authentication_secret_name_ set in the `CostManagement` custom resource configured in the next steps.
+
. Configure the Metering Operator.
+
Cost management uses the Metering Operator to create, collect, package, and upload metrics to cost management. In order for metering to work properly, configure `operator-metering` using the https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html-single/metering/index#configuring-metering[OpenShift documentation] to create a MeteringConfig resource.
+
. Configure the Cost Management Operator by creating the `CostManagement` and `CostManagementData` custom resources.
+
Creating these resources also starts the roles that create the resources to obtain the usage reports (metrics). This takes about an hour to run and the reports are collected, packaged, and uploaded every six hours.
+
[NOTE]
====
The Cost Management Operator requires the `clusterID`, `reporting_operator_token_name`, and `authentication_secret_name` to be specified in a `CostManagement` custom resource.
====
+
.. Copy the following `CostManagement` resource template and save it to a file called `cost-mgmt-resource.yaml`:
+
----
apiVersion: cost-mgmt.openshift.io/v1alpha1
kind: CostManagement
metadata:
  name: cost-mgmt-setup
spec:
  clusterID: '123a45b6-cd8e-9101-112f-g131415hi1jk'
  reporting_operator_token_name: 'reporting-operator-token-123ab'
  validate_cert: 'false'
  authentication: 'basic'
  authentication_secret_name: 'basic_auth_creds-123ab'
----
+
.. Edit the following values in your `cost-mgmt-resource.yaml` file:
+
* The `clusterID` value to your cluster ID. Obtain your cluster ID by running: 
+
----
$ oc get clusterversion -o jsonpath='{.items[].spec.clusterID}{"\n"}'
----
+
* The `reporting_operator_token_name` to the `reporting-operator-token` secret name inside the `openshift-metering` namespace. Obtain this by running: 
+
----
$ oc get secret -n openshift-metering | grep reporting-operator-token
----
+
[NOTE]
====
Depending on your configuration, this command can return two token names. You can use either to configure the Cost Management Operator.
====
* Specify the authentication type you are using (`token` or `basic`). If you are using `token` authentication, you can remove the authentication field as token authentication is the default.
* Change the `authentication_secret_name` to the name of your authentication secret you created earlier.
+
.. Deploy the `CostManagement` resource:
+
----
$ oc create -f cost-mgmt-resource.yaml
----
+
.. Create a `CostManagementData` resource to start the collection. Copy the following template and save it as `cost-mgmt-data-resource.yaml`:
+
----
apiVersion: cost-mgmt-data.openshift.io/v1alpha1
kind: CostManagementData
metadata:
  name: cost-mgmt-data-example
----
+
.. Deploy the `CostManagementData` resource:
+
----
$ oc create -f cost-mgmt-data-resource.yaml
----
+
The Cost Management Operator will now create, collect, package, and upload your OpenShift usage reports to cost management.
+
. When configuration is complete, enter the cluster identifier into the cloud.redhat.com *Sources* wizard, click *Next*.
+
[NOTE]
====
The cluster identifier can be found in *Help* > *About* in OpenShift.
====
+
. In the cloud.redhat.com *Sources* wizard, review the details and click *Finish* to add the OpenShift Container Platform cluster to cost management.


.Additional resources

* See https://docs.openshift.com/container-platform/4.3/operators/olm-understanding-operatorhub.html[Understanding the OperatorHub] in the OpenShift documentation for more information about Operators and OperatorHub.



