// Module included in the following assemblies:
//
// assembly-adding-openshift-container-platform-source.adoc
:_content-type: PROCEDURE
:experimental:


[id="configuring-the-operator-instance-for-a-new-installation_{context}"]
= Configuring the operator instance for a new installation

[role="_abstract"]
Use the {openshift} web console to configure the +{operator}+ instance after it is installed.

.Prerequisites
* You are logged into the {openshift} web console with cluster administrator privileges.
* The *{operator-formal}* appears in the *Installed Operators* tab.

.Procedure

. Under the *Name* heading in the list of installed operators, click the *{operator-formal}* link. The *Installed Operators > Operator Details* window appears for *{operator-formal}*.
. In the *Details* window, click *+{nbsp}Create Instance*.
. A *{operator-formal} > Create {operator-config}* window appears.
. Click the *YAML view* radio button to view and modify the contents of the YAML configuration file.
. When you create a new {product-title} instance for the {operator-formal}, make the following modifications in the YAML configuration file.
. Locate the following two lines in the YAML file.
+
----
    create_source: false
    name: INSERT-SOURCE-NAME
----
+
.. Change `false` to `true`.
.. Change `INSERT-SOURCE-NAME` to the new name of your source.
+
.Example
----
    create_source: true
    name: my-openshift-cost-source
----
+
[NOTE]
====
The value entered for `INSERT-SOURCE-NAME` will be the name of the source in {product-title}. Leaving this value as `INSERT-SOURCE-NAME` is acceptable, but it is recommended to change it to something more identifiable, especially when installing the operator in multiple clusters.
====
. Click the *Create* button. These actions create a new source for {product-title} that will appear in the {platform-title} {product-title} application.
