// Module included in the following assemblies:
//
// assembly-adding-a-restricted-network-source.adoc
:_module-type: PROCEDURE
:experimental:

[id="configuring-cost-operator-on-a-restricted-network_{context}"]
= Configuring Cost Operator on a restricted network


[role="_abstract"]
After the +{operator}+ is installed, you must configure it to run on a restricted network.

.Prerequisites

* +{operator}+ installed.
* You are logged into the {openshift} web console with cluster administrator privileges.

.Procedure

. From the {openshift} web console, select *Operators > Installed Operators > +{operator}+ > {operator-config} > Create Instance*.

. Specify the desired storage. If not specified, the operator will create a default persistent volume claim called `+{operator}+-data` with *10Gi* of storage.
+
[NOTE]
====
To configure the +{operator}+ to use or create a different PVC, update the `volume_claim_template` configuration in *YAML view*.
====

. Select *YAML view*.

. Specify the maximum number of reports to store using `max_reports_to_store`, and time between report generation in minutes using `upload_cycle`.
+
[source,yaml]
----
    packaging:
      max_reports_to_store: 30
      max_size_MB: 100
----
+
[source,yaml]
----
    upload:
      upload_cycle: 360
----
+
[IMPORTANT]
====
The +{operator}+ creates one report every *360 minutes* by default. Therefore, the default value of *30* reports and *360* minutes gives you *7.5 days* of reports.

Any report generated after the total number specified will replace the oldest report in storage. Make sure to download generated reports from your PVC before they are lost.
====

. Set `upload_toggle` to `false`.
+
[source,yaml]
----
    upload:
      upload_cycle: 360
      upload_toggle: false
----

. Replace the configuration in the `source` section with empty brackets.
+
[source,yaml]
----
    source: {}
----

. Replace the configuration in the `authentication` section with empty brackets.
+
[source,yaml]
----
    authentication: {}
----

. Click *Create*.

.Verification steps

. Select the *{operator-config}* you created.

. Select *YAML view*.

. Verify that a report has been created in the `packaging` section.
+
[source,yaml]
----
    packaging:
      last_successful_packaging_time: `current date and time`
      max_reports_to_store: 30
      max_size_MB: 100
      number_of_reports_stored: 1
      packaged_files:
        - >-
            /tmp/+{operator}+-reports/upload/YYYYMMDDTHHMMSS-cost-mgmt.tar.gz

----
+
[NOTE]
====
+{operator}+ will generate an initial report after it is configured. Generated reports will be listed under `packaged_files`.
====
