// Module included in the following assemblies:
//
// assembly-cost-management-next-steps.adoc
:_content-type: CONCEPT
:experimental:

[id="configure-cost-models-next-step_{context}"]
= Configure cost models to accurately report costs

[role="_abstract"]
Now that you have configured your sources to collect cost and usage data into {product-title}, you can configure cost models to associate prices to metrics and usage, and fine-tune the costs of running your cloud.

A cost model is a framework used to define the calculations for the costs stored in {product-title}, using raw costs and metrics. Costs generated by a cost model can be recorded, categorized and distributed to specific customers, business units or projects.

From the {link-cost-models-app} area of {product-title}, you can:

* Classify your costs as infrastructure or supplementary costs.
* Capture monthly costs for OpenShift nodes and clusters.
* Apply a markup to account for additional support costs.
* Learn how to configure a cost model in _{link-cost-models}_.
