// Module included in the following assemblies:
// assembly_adding_azure_sources.adoc

[id="configuring_an_azure_daily_export_schedule"]
[[configuring_an_azure_daily_export_schedule]]
== Configuring a daily Azure data export schedule

// The URL for this procedure needs to go in the UI code in the Sources dialog.

Create a recurring task to export your cost data on a daily basis automatically to your Azure storage account, where cost management will retrieve the data. 

. In Azure, add a new export as described in the instructions in the https://docs.microsoft.com/en-us/azure/cost-management/tutorial-export-acm-data[Azure article] _Create and manage exported data_.
* For *Export type*, select *Daily export of billing-period-to-date costs*.
* For *Storage account*, select the account you created earlier. 
* Enter any value for the container name and directory path for the export. These values provide the tree structure in the storage account where report files are stored.
* Click *Run now* to start exporting data to the Azure storage container.
. In cost management, click *Next* when you have created the export schedule and review the source details. 
. Click *Finish* to complete adding the Azure source to cost management.

After the schedule is created, cost management will begin polling Azure for cost data, which will appear on the cost management dashboard.


