// Module included in the following assemblies:
//
// assembly-using-cost-models.adoc
:_content-type: REFERENCE
:experimental:


[id="cost-model-terms_{context}"]
= Cost model concepts

[role="_abstract"]
These terms and concepts are important for understanding {product-title}’s cost model workflow.

Cost model:: A cost model is a framework used to define the calculations for the costs stored in {product-title}, using raw costs and metrics. The cost model is used for budgeting and accounting, and also the visualization and analysis of costs — in {product-title}, it provides the basis for the cost information that the user will view. Costs generated by a cost model can be recorded, categorized and allocated to specific customers, business units or projects.

[[cost-layers]]
== Cost layers

Costs can be created at different layers of the environment. In {product-title}, all costs can be classified as either infrastructure or supplementary costs (including your costs that are not identified as infrastructure). In your cost model, you can choose to allocate and present your costs as any of those cost layers. As a result, you can customize what {product-title} shows on each details page.

Infrastructure cost:: This cost can come from two different sources:
* Costs directly reported by a cloud provider, through an Amazon (AWS) Cost and Usage Report, Microsoft Azure or Google Cloud export. In the current version of cost management, all cloud costs are considered infrastructure costs.
* Costs calculated from a price list for rates specifically marked as infrastructure.
+
[NOTE]
====
OpenShift Container Platform node and cluster cost per month rates are classified as infrastructure cost by default, but can be optionally classified as supplementary.
====

Supplementary cost:: All costs not directly attributed to infrastructure are identified as supplementary costs. In the current version of {product-title}, these costs come from applying a price list to metrics obtained from an OpenShift cluster. The rates in the price list must be specified as supplementary. This is the default for all OpenShift costs except node and cluster cost per month.


[[cost-model-terminology]]
== Cost model terminology

Cost:: The sum of infrastructure and supplementary costs. This can be thought of as the "total cost" for the filtered data being shown (for example, cost for a particular account, region, or service).

Raw cost:: The costs reported by a cloud provider without any cost model calculations applied.

//Previously: Raw metrics and costs:: Raw metrics and costs are the metrics and costs provided by a third party that have not been modified in any way, such as the AWS costs provided by the AWS Cost and Usage Report files or the API, and the OpenShift metrics provided through Operator Metering.

Markup:: The portion of cost calculated by applying markup or discount to infrastructure raw cost in the {product-title} application.
+
_Example: For a raw cost of $100 and a markup of 10%, the markup would be $10, and the cost would be $110 (sum of both)._

// Previously: In the {product-title} application, the markup is the ratio, positive or negative, between the base cost and the calculated cost.

Usage cost:: The portion of cost calculated by applying hourly or monthly price list rates to metrics.
+
_Example: For a metric of 100 core-hours and a rate of $1/core-hour, the usage cost would be $100._

Monthly cost:: The portion of cost calculated by applying monthly price list rates to metrics returned as part of usage cost. Monthly cost can be configured for OpenShift nodes or clusters in a cost model to account for subscription costs, for example.
+
Monthly costs are currently shown as part of the usage costs in the {product-title} API and interface.
+
[NOTE]
====
These costs are not currently amortized over the reported period in the API, so when viewing a daily breakdown of cost, monthly costs will only show on the first of the month.
====
+
_Example: For an OpenShift cluster with 10 nodes at a rate of $10,000 per node per month, the monthly cost would be $100,000._

Price list:: A list of rates used within the application’s cost model to calculate the usage cost of resources.

Distributed costs:: The costs calculated by the cost model are distributed to higher level application concepts, such as project, account, service, and so on. How the costs are distributed depends on the cost type (infrastructure or supplementary) assigned in the cost model.
