// Module included in the following assemblies:
// assembly_adding_aws_sources.adoc
[id="creating_an_aws_s3_bucket"]
[[creating_an_aws_s3_bucket]]
== Creating an S3 bucket for reporting

Cost management requires an Amazon S3 bucket with permissions configured to store billing reports.

Log into your AWS master account to begin configuring cost and usage reporting:

. In the AWS S3 console, create a new S3 bucket or use an existing bucket. If you are configuring a new S3 bucket, accept the default settings.
. In the AWS Billing console, create a Cost and Usage Report that will be delivered to your S3 bucket. Specify the following values (and accept the defaults for any other values):
+
* Report name: _<any-name>_ (note this name as you will use it later)
* Additional report details: Include resource IDs
* S3 bucket: <the S3 bucket you configured previously>
* Time granularity: Hourly
* Enable report data integration for: Amazon Redshift, Amazon QuickSight (do not enable report data integration for Amazon Athena)
* Compression type: GZIP
* Report path prefix: cost
+
[NOTE]
====
See the AWS _Billing and Cost Management_ documentation for more details on configuration.
====
+
. In the cloud.redhat.com platform, open the *Sources* menu (https://cloud.redhat.com/settings/sources/) to begin adding an AWS source to cost management:
.. Navigate to *Sources* and click *Add a source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *Cost Management* as the application and *Amazon Web Services (AWS)* as the source type. Click *Next*.
.. Paste the name of your S3 bucket and click *Next*.



