// Module included in the following assemblies:
// assembly_adding_azure_sources.adoc
[id="creating_an_azure_storage_account"]
[[creating_an_azure_storage_account]]
== Creating an Azure resource group and storage account

// The URL for this procedure needs to go in the UI code in the Sources dialog.

Cost export data is written to a storage account, which exists within a resource group. The resource group must be accessible by cost management in order to read the Azure cost data.

Create a new storage account in Azure to contain the cost data and metrics that cost management will collect. This requires a resource group; Red Hat recommends creating a dedicated resource group for this storage account.

. In the cloud.redhat.com platform, open the *Sources* menu (https://cloud.redhat.com/settings/sources/) to begin adding an Azure source to cost management:
.. Navigate to *Sources* and click *Add a source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *Cost Management* as the application and *Microsoft Azure* as the source type. Click *Next*.
. Create a resource group and storage account in your Azure account using the instructions in the See https://docs.microsoft.com/en-us/azure/storage/common/storage-quickstart-create-account?tabs=azure-portal[Azure documentation] _Create a storage account_. 
+
//Still need this note?
[IMPORTANT]
====
Make a note of the resource group and storage account. They will be needed in subsequent steps.
====
. In the cloud.redhat.com *Sources* wizard, enter the *Resource group name* and *Storage account name* and click *Next*.

////
NOTE: Commenting out for now as these steps aren't in the wizard (Feb 17, 2020)
.. Enter the storage account name and resource group you just created.
. In Azure Cloud Shell, run the following command to obtain your Subscription ID: 
+
----
$ az account show --query "{subscription_id: id }"
----
+
. In the cloud.redhat.com *Sources* wizard, enter your Subscription ID in the sources wizard and click *Next*.
////

