// Module included in the following assemblies:
//
// assembly-adding-aws-sources.adoc
:_content-type: PROCEDURE
:experimental:


[id="creating-an-aws-s3-bucket_{context}"]
= Creating an S3 bucket for reporting

[role="_abstract"]
Cost management requires an Amazon S3 bucket with permissions configured to store billing reports.

Log into your AWS account to begin configuring cost and usage reporting:

. In the AWS S3 console, create a new S3 bucket or use an existing bucket. If you are configuring a new S3 bucket, accept the default settings.
. In the AWS Billing console, create a Cost and Usage Report that will be delivered to your S3 bucket. Specify the following values (and accept the defaults for any other values):
+
* Report name: _<any-name>_ (note this name as you will use it later)
* Additional report details: Include resource IDs
* S3 bucket: _<the S3 bucket you configured previously>_
* Time granularity: Hourly
* Enable report data integration for: Amazon Redshift, Amazon QuickSight (do not enable report data integration for Amazon Athena)
* Compression type: GZIP
* Report path prefix: cost
+
[NOTE]
====
See the AWS _Billing and Cost Management_ documentation for more details on configuration.
====
+
. From {platform-title}, open the *Sources* menu ({link-sources}) to begin adding an AWS source to {product-title}:
.. Navigate to *Sources* and click *Add a source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *{product-title}* as the application and *Amazon Web Services (AWS)* as the source type. Click *Next*.
.. Paste the name of your S3 bucket and click *Next*.
