// Module included in the following assemblies:
// assembly_adding_aws_sources.adoc
[id="creating_an_aws_s3_bucket"]
[[creating_an_aws_s3_bucket]]
== Creating an S3 bucket for reporting

// Add this URL to the UI. Link to the double bracket label: creating_an_aws_s3_bucket

Cost management requires an Amazon S3 bucket with permissions configured to store billing reports.

Log into your AWS master account to begin configuring cost and usage reporting:

. In the AWS S3 console, create a new S3 bucket or use an existing bucket. If you are configuring a new S3 bucket, accept the default settings.
. In the AWS Billing console, create a Cost and Usage report that will be delivered to your S3 bucket. Specify the following values (and accept the defaults for any other values):
+
----
Report name: _<any-name>_ (note this name as you will use it later)
Additional report details: Include resource IDs
S3 bucket: <the S3 bucket you configured previously>
Time granularity: Hourly
Enable report data integration for: Amazon Redshift, Amazon QuickSight
Report path prefix: (leave blank)
----
+
[NOTE]
====
See the AWS _Billing and Cost Management_ documentation for more details on configuration.
====
+
// These steps will need updating for the changes in the global sources flow - ie. enter name, select AWS, select Cost...);
. In the cost management application (cloud.redhat.com):
.. Navigate to *Settings > Cost Management Sources* and click *Add source* to open the wizard.
.. Provide a name for your source, select *Amazon Web Services (AWS)* and click *Next*.
.. Paste the name of your S3 bucket and click *Next*.



