// Module included in the following assemblies:
// assembly_adding_azure_sources.adoc
:_module-type: PROCEDURE
:experimental:

[id="creating-an-azure-storage-account_{context}"]
= Creating an Azure resource group and storage account

[role="_abstract"]
Cost export data is written to a storage account, which exists within a resource group. The resource group must be accessible by {product-title} in order to read the Azure cost data.

Create a new storage account in Azure to contain the cost data and metrics that {product-title} will collect. This requires a resource group; Red Hat recommends creating a dedicated resource group for this storage account.

[NOTE]
====
You must have a Red Hat account user with Sources Administrator entitlements before you can add sources to {product-title}.
====

. In the {platform} platform, open the *Sources* menu (https://cloud.redhat.com/settings/sources/) to begin adding an Azure source to {product-title}:
.. Navigate to *Sources* and click *Add a source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *{product-title}* as the application and *Microsoft Azure* as the source type. Click *Next*.
. Create a resource group and storage account in your Azure account using the instructions in the See link:https://docs.microsoft.com/en-us/azure/storage/common/storage-quickstart-create-account?tabs=azure-portal[Azure documentation] _Create a storage account_.
+
//Still need this note?
[IMPORTANT]
====
Make a note of the resource group and storage account. They will be needed in subsequent steps.
====
[start=3]
. In the {platform} *Sources* wizard, enter the *Resource group name* and *Storage account name* and click *Next*.
