// Module included in the following assemblies:
//
// assembly-adding-a-restricted-network-source.adoc
:_module-type: PROCEDURE
:experimental:

[id="proc_downloading-reports_{context}"]
= Downloading cost reports


[role="_abstract"]
If the `koku-metrics-operator` is configured to run in a restricted network, copy the reports from the PVC where they are temporarily stored to a workstation with unrestricted network access for upload to {platform}.

[NOTE]
====
The default configuration saves one week of reports. Therefore, download the reports locally and upload them to {platform} weekly to prevent loss of metrics data.
====

.Prerequisites

* Workstation with unrestricted network access.
* `koku-metrics-operator` reports in your PVC.

.Procedure

. Create the following pod with `claimName` matching the PVC containing the report data:
+
[source,bash]
----
kind: Pod
apiVersion: v1
metadata:
  name: volume-shell
  namespace: koku-metrics-operator
spec:
  volumes:
  - name: koku-metrics-operator-reports
    persistentVolumeClaim:
      claimName: koku-metrics-operator-data
  containers:
  - name: volume-shell
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - name: koku-metrics-operator-reports
      mountPath: /tmp/koku-metrics-operator-reports
----

. Use `rsync` to copy all of the files from the PVC to a local folder.
+
[source,bash]
----
$ oc rsync volume-shell:/tmp/koku-metrics-operator-reports/upload local/path/to/save/folder
----

. Confirm that the files have been copied.

. Connect to the pod and delete the contents of the upload folder.
+
[source,bash]
----
$ oc rsh volume-shell
$ rm /tmp/koku-metrics-operator-reports/upload/*
----

. (Optional) Delete the pod that was used to connect to the PVC.
+
[source,bash]
----
$ oc delete -f volume-shell.yaml
----

[role="_additional-resources"]
.Additional resources

* For more information on persistent volume claims, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/storage/understanding-persistent-storage[Understanding persistent storage].
