// Module included in the following assemblies:
// assembly_adding_ocp_sources.adoc

[id="downloading_and_configuring_usage_collector_ocp"]
[[downloading_and_configuring_usage_collector_ocp]]
== Downloading and configuring the Usage Collector

// The URL for this procedure needs to go in the UI code in the Sources dialog.

The Usage Collector connects to your OpenShift cluster and collects usage data required for {product-title}.

The Usage Collector is an Ansible playbook wrapped in a minimal script that performs setup and collecting tasks. During the setup phase, configuration is stored for connectivity to the OpenShift cluster and usage report resources are created to enable the ongoing collection of usage data.

During the collection phase, usage data is retrieved from the Operator Metering endpoint and compressed into a package that is uploaded for processing by {product-title} via the Red Hat Insights Client.

. Download the Usage Collector from _https://github.com/project-koku/korekuta/archive/master.zip_ on the same system where the Red Hat Insights Client was installed, using your browser or with the following command:
+
----
# curl -LOk https://github.com/project-koku/korekuta/archive/master.zip
----
+
. Unzip the tool:
+
----
# unzip master.zip
----
+
. Navigate to the _korekuta-master_ directory to find the _ocp_usage.sh_ script.
+
----
# cd korekuta-master
----
+
. Run the _ocp_usage.sh_ script with your cluster’s variables to set up the Usage Collector.
+
[NOTE]
====
To configure the Usage Collector, you need the following information:

* OpenShift API endpoint (e.g. https://api.openshift-prod.mycompany.com)
* OpenShift reporting-operator token file path
* OpenShift Operator Metering namespace (e.g. metering)
* The URL of the route exposed for the reporting operator in the Operator Metering namespace (e.g. https://metering.metering.api.ocp.com)
* sudo password for installing dependencies
====
+
Use the following example, substituting values for your OpenShift API endpoint, Operator Metering namespace, metering-operator token file path, and Metering API endpoint:
+
----
# ./ocp_usage.sh --setup
-e OCP_API="https://api.openshift-prod.mycompany.com"
-e OCP_METERING_NAMESPACE="openshift-metering"
-e OCP_TOKEN_PATH="/path/to/ocp_usage_token"
-e METERING_API="https://metering.metering.api.ocp.com”
----
+
[NOTE]
====
If the oc command line is installed in a different location from _/usr/bin/oc_ on your system, specify the path using _-e OCP_CLI=</path/to/oc>_ when executing the _ocp_usage.sh_ command.

You will be prompted for your sudo password and the Ansible playbook will execute to capture the configuration information and create the usage reports on your OpenShift cluster. When complete you will see the following message:


----
TASK [setup : Display New Cluster Identifier] **********************************
ok: [localhost] => {
    "msg": "Use the following value, <YOUR_OCP_IDENTIFIER>, for the cluster identifier when configuring an OCP provider in {product-title}."
}
----
====
+
. Copy the cluster identifier to enter into the {platform} *Sources* screen and click *Next*.
+
[NOTE]
====
The cluster identifier value is also stored in _~/.config/ocp_usage/config.json_.
====
