// Module included in the following assemblies:
//
// assembly_managing_cost_data_tagging.adoc

// Base the file name and the ID on the module title. For example:
// * file name: exporting_data_by_tag_category.adoc
// * ID: [id="exporting_data_by_tag_category"]
// * Title: = Exporting data by tag category

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="exporting_data_by_tag_category_{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Exporting data by tag category

Tags allow you to customize your view of cost data. This is useful when you want to investigate further why certain resources show an increase in cost, or data looks abnormal.

This example shows how to view data for specific OpenShift resources, and export the data to your desired reporting tool.

.Prerequisites

* Configure tags on your sources. For tips and configuration instructions, see LINK.

.Procedure

. From the *OpenShift details* menu, click the filter button and select *Tag*.
. In the *Choose key* dropdown list, select the key to filter by. For example, select _version_. Selecting a tag key reveals another dropdown to choose the value to filter by.
. In the *Choose value* dropdown list, select one or more values to filter by. For example, select _qe_ and _dev_ to show cost data for OpenShift resources with these tags.
//Is that right? How can this be more useful?
. To export data about your resources, check the boxes next to each tag you want to export data for. Click *Export* to open the export options dialog.
. Specify a daily or monthly aggregate and click *Generate and download*.

The CSV file will download to your local system, and you can use it in your desired reporting tool.

[NOTE]
====
You can also export your data as a .csv file from the menu:more options[Export data] menu.
====

Click *Clear all filters* to reset your OpenShift details view.



//.Additional resources

//* A bulleted list of links to other material closely related to the contents of the procedure module.

