// Module included in the following assemblies:
// assembly-using-cost-explorer.adoc
:_content-type: Concept
:experimental:

[id="filtering-cost-data-cost-explorer_{context}"]
= Filtering cost data with Cost Explorer

[role="_abstract"]
Using the filter options in {link-cost-explorer-app} you can customize what data to view. 

This example shows how to see the costs related to an {openshift} project from the previous 90 days.

.Prerequisites

* Your OpenShift cluster added as a {product-title} data source. See _{link-adding-ocp}_ for instructions.
* Your cloud infrastructure account added as a {product-title} data source. See _{link-adding-sources}_ for instructions for your cloud provider type.


.Procedure

. From the *{link-cost-explorer-app}*, select a *Perspective*. For example, select _All OpenShift Cost_  to view your cumulative openshift costs. 
. Select a grouping. For example, with {openshift} you can group by _Project_, _Node_, _Cluster_, or _Tag_. With other perspective views, the *Group by* options will change accordingly. 
. If desired, specify one or more _Projects_, _Nodes_, _Clusters_, or _Tags_ by name.  
. Select _Last 90 days_ to view the cost data from the previous 90 days. 
. Repeat these steps for different perspectives and groupings to better understand your costs. 

.Next Steps

After filtering your data, you can export it into a CSV file. See xref:exporting-cost-data-cost-explorer_cost-explorer[] for more information. 

