// Module included in the following assemblies:
//
// assembly-configuring-tags-and-labels-in-cost-management.adoc
:_module-type: CONCEPT
:experimental:

[id="how-cost-associates-tags_{context}"]
= How {product-title} associates tags

[role="_abstract"]
Tags in AWS and Azure and labels in OpenShift consist of key:value pairs. When the key:value pairs match, the AWS/Azure and OpenShift costs are automatically associated by {product-title}. Tag matching in {product-title} is not case sensitive: for example, an AWS resource tagged _APP_ and an OpenShift resource tagged _app_ are a match:


.Example: Tag matching
[options="header"]
|====
|Source and resource type|Key|Value
|AWS resource (RDS)|APP|Cost-Management
|OpenShift pod|app|cost-management
|====


If an AWS resource tag matches with multiple OpenShift projects, the cost and usage of that resource are split evenly between the matched projects.

Note that this is not the case with AWS compute resources that are matched via the instance ID-node relationship. In that case, cost and usage are broken down using information about a project’s resource consumption within the OpenShift cluster.

By default, {product-title} tracks AWS compute usage and costs by associating the Amazon EC2 instance ID or Azure virtual machine instance ID with the OpenShift Container Platform node running on that instance.


== Tag matching hierarchy in {product-title}

To identify your OpenShift resources running on AWS or Azure instances, {product-title} matches tags between sources in the following order:

. Direct resource matching (AWS EC2 instance ID or Azure virtual machine instance ID)
. Special OpenShift tags
. Custom tags


=== Direct resource matching (instance ID)

The sources apply these identifiers automatically. This form of tagging provides a direct link between Azure or AWS instances and OpenShift nodes.


AWS assigns every EC2 instance a resource identifier (a number such as `i-01f44b3d90ef90055`). OpenShift nodes are matched directly to the AWS EC2 instance the cluster is running on using the AWS resource identifier. The OpenShift reports in {product-title} (generated from Prometheus data) include this identifier for nodes. Similarly in Azure, each virtual machine instance ID is included in the OpenShift reports for {product-title}.


=== Special OpenShift tags

There are three special-case AWS tags you can use to associate cost with OpenShift:

* `openshift_cluster`
* `openshift_node`
* `openshift_project`

These tags have matching priority over custom tags, and are especially useful in differentiating the costs of different OpenShift clusters running on the same AWS instance.

To use this tagging method to identify an OpenShift cluster, tag your AWS instance with the key `openshift_cluster`, and provide the OpenShift source name as the value. In the following example, the name of OpenShift source in the {product-title} application is `dev-cluster`:


.Example: Special OpenShift tags
[options="header"]
|====
|Source and resource type|Key|Value
|AWS resource (RDS)|`openshift_cluster`|`dev-cluster`
|OpenShift cluster|
No tags needed. This will match if the name of the OpenShift source in {product-title} is  `dev-cluster`.

|No tags needed.
|====


=== Custom tags

You can use any key:value combination as tags, and {product-title} will associate identical tag key and values together. You can then group costs by tag key, account, service, region, and more to view your costs and charge for that tag.

.Example: Custom tags
[options="header"]
|====
|Source and resource type|Key|Value
|AWS resource (RDS)|`team`|`engineering`
|OpenShift pod|`team`|`engineering`
|====



//.Additional resources
