// Module included in the following assemblies:
//
// assembly-configuring-tags-and-labels-in-cost-management.adoc
:_content-type: CONCEPT
:experimental:

[id="how-cost-associates-tags_{context}"]
= How {product-title} associates tags

[role="_abstract"]
Tags in AWS and Azure and labels in OpenShift consist of key:value pairs. When the key:value pairs match, the AWS/Azure and OpenShift costs are automatically associated by {product-title}. Tag matching in {product-title} is not case sensitive: for example, an AWS resource tagged _APP_ and an OpenShift resource tagged _app_ are a match:


.Example: Tag matching
[options="header"]
|====
|Source and resource type|Key|Value
|AWS resource (RDS)|APP|Cost-Management
|OpenShift pod|app|cost-management
|====


If an AWS resource tag matches with multiple OpenShift projects, the cost and usage of that resource are split evenly between the matched projects.

Note that this is not the case with AWS compute resources that are matched via the instance ID-node relationship. In that case, cost and usage are broken down using information about a project’s resource consumption within the OpenShift cluster.

By default, {product-title} tracks AWS compute usage and costs by associating the Amazon EC2 instance ID or Azure virtual machine instance ID with the OpenShift Container Platform node running on that instance.
