// Module included in the following assemblies:
// assembly-adding-ocp-sources.adoc
:_module-type: PROCEDURE
:experimental:

[id="installing-cost-mgmt-operator_{context}"]
== Installing the {product-title} Operator

[role="_abstract"]
The {product-title} Operator collects the metrics required for {product-title}.

Begin adding your OpenShift Container Platform cluster as a source to {product-title}, then install the {product-title} Operator from OperatorHub.

[NOTE]
====
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators[Operators] in the OpenShift documentation for more information about Operators and OperatorHub.
====

.Prerequisites

* OpenShift Container Platform 

.Procedure

. From {platform-title}, open the *Sources* menu ({link-sources}) to begin adding an OpenShift source to {product-title}:
.. Navigate to *Sources* and click *Add source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *{product-title}* as the application and *OpenShift Container Platform* as the source type. Click *Next*.
. In OpenShift, create a namespace called `openshift-metering` if one does not exist, and label the namespace with `openshift.io/cluster-monitoring=true`.
. In OpenShift, install the {product-title} Operator in the `openshift-metering` namespace, using either the OpenShift web console (search for _cost management_ in OperatorHub) or the CLI.
+
[IMPORTANT]
====
You must install the {product-title} Operator in the `openshift-metering` namespace. Other namespaces are not supported for installation.
====
+
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[Adding Operators to a cluster] in the OpenShift documentation for instructions for installing an Operator.


.Additional resources

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/metering[Metering] in the OpenShift documentation for more information about installing Metering.
