// Module included in the following assemblies:
//
// assembly-adding-a-restricted-network-source.adoc
:_module-type: PROCEDURE
:experimental:


[id="proc_installing-koku-metrics-operator-on-a-restricted-network_{context}"]
= Installing the Koku Metrics Operator on a restricted network


[role="_abstract"]
For OpenShift Container Platform clusters that are installed on restricted networks, Operator Lifecycle Manager (OLM) by default cannot access the koku-metrics-operator hosted remotely because those remote sources require full Internet connectivity. Therefore, OLM must be configured to install and run local sources.

.Prerequisites

* OpenShift Container Platform cluster installed.
* Workstation with unrestricted network access.
* You are logged into the OpenShift Container Platform web console with cluster administrator privileges.

.Procedure

. Complete the following OpenShift Container Platform procedure to create a local mirror of the `koku-metrics-operator`: *link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/operators/administrator-tasks#olm-restricted-networks[_Using Operator Lifecycle Manager on restricted networks_]*.
+
[NOTE]
====
The `koku-metrics-operator` is found in the `community-operators` Catalog in the `registry.redhat.io/redhat/community-operator-index:latest` index.

Red Hat recommends pruning unwanted objects from the index before pushing to the mirrored registry. Make sure you keep the `koku-metrics-operator` package.
====

. Log in to the OpenShift Container Platform web console and click *Operators > OperatorHub*.
. Search for and locate *Koku Metrics Operator*.
. Click the *Koku Metrics Operator* tile.
. If an information panel appears with the *Community Operators* message, click *Continue*.
. When the *Install Operator* window appears, you must select the `koku-metrics-operator` namespace for installation. If the namespace does not yet exist, it is created for you.
. Click btn:[Install].


.Verification steps

* After a short wait, *Koku Metrics Operator* appears in the *Installed Operators* tab under *Project: all projects* or *Project: koku-metrics-operator*.

[role="_additional-resources"]
.Additional resources

* For more details on the Operator Lifecycle Manager, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/operators/understanding-operators#operator-lifecycle-manager-olm[_.What is Operator Lifecycle Manager?_]
