// Module included in the following assemblies:
// assembly_adding_ocp_sources.adoc
[id="installing_cost_mgmt-operator"]
[[installing_cost_mgmt-operator]]
== Installing the Cost Management Operator

The Cost Management Operator collects the metrics required for cost management.    

Begin adding your OpenShift Container Platform cluster as a source to cost management, then install the Cost Management Operator from OperatorHub.

[NOTE]
====
See https://docs.openshift.com/container-platform/4.3/operators/olm-understanding-operatorhub.html[Understanding the OperatorHub] in the OpenShift documentation for more information about OperatorHub.
====

.Prerequisites

* OpenShift Container Platform 4.3 or newer

.Procedure

. In the cloud.redhat.com platform, open the *Sources* menu (https://cloud.redhat.com/settings/sources/) to begin adding an OpenShift source to cost management:
.. Navigate to *Sources* and click *Add source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *Cost Management* as the application and *OpenShift Container Platform* as the source type. Click *Next*.
. In OpenShift, install the Cost Management Operator on your cluster, using either the OpenShift web console (search for _cost management_ in OperatorHub) or the CLI.
+
[IMPORTANT]
====
You must install the Cost Management Operator in the `openshift-metering` namespace. Other namespaces are not supported for installation.
====
+
See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/operators/olm-adding-operators-to-a-cluster[Adding operators to a cluster] in the OpenShift documentation for instructions for installing an Operator.




