// Module included in the following assemblies:
//
// assembly-adding-openshift-container-platform-source.adoc
:_content-type: PROCEDURE
:experimental:

[id="installing-cost-operator_{context}"]
= Installing the cost operator

[role="_abstract"]
Install the *{operator-formal}* from the {openshift} web console.

.Prerequisites
* You are logged into the {openshift} web console with cluster administrator privileges.

.Procedure

. Login to the {openshift} web console and click on the *Operators > OperatorHub* tab.
. Search for and locate *{operator-formal}*.
. Click on the displayed *{operator-formal}* tile.
ifdef::koku[]
. If an information panel appears with the Community Operators message, click *Continue*.
endif::koku[]
. When the *Install Operator* window appears, you must select the +{operator}+ namespace for installation. If the namespace does not yet exist, it is created for you.
. Click on the *Install* button.
. After a short wait, *{operator-formal}* appears in the *Installed Operators* tab under *Project: all projects* or *Project: {operator}*.

[IMPORTANT]
====
If a proxy with a custom CA certificate is configured, additional configuration  is required to inject this certificate into {operator-formal}. 
See, link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/administrator-tasks#olm-inject-custom-ca_olm-configuring-proxy-support[_Injecting a custom CA certificate_] in the {openshift} documentation for details. 
====
