// Module included in the following assemblies:
// assembly-adding-ocp-sources.adoc
:_module-type: PROCEDURE
:experimental:

[id="installing-cost-mgmt-operator_{context}"]
== Installing the Cost Management Operator

[role="_abstract"]
The Cost Management Operator collects the metrics required for cost management.

Begin adding your OpenShift Container Platform cluster as a source to cost management, then install the Cost Management Operator from OperatorHub.

[NOTE]
====
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/operators[Operators] in the OpenShift documentation for more information about Operators and OperatorHub.
====

.Prerequisites

* OpenShift Container Platform 4.3 or 4.4

.Procedure

. In the {platform} platform, open the *Sources* menu (https://cloud.redhat.com/settings/sources/) to begin adding an OpenShift source to cost management:
.. Navigate to *Sources* and click *Add source* to open the Sources wizard.
.. Enter a name for your source and click *Next*.
.. Select *Cost Management* as the application and *OpenShift Container Platform* as the source type. Click *Next*.
. In OpenShift, create a namespace called `openshift-metering` if one does not exist, and label the namespace with `openshift.io/cluster-monitoring=true`.
. In OpenShift, install the Cost Management Operator in the `openshift-metering` namespace, using either the OpenShift web console (search for _cost management_ in OperatorHub) or the CLI.
+
[IMPORTANT]
====
You must install the Cost Management Operator in the `openshift-metering` namespace. Other namespaces are not supported for installation.
====
+
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/operators/administrator-tasks#olm-adding-operators-to-a-cluster[Adding Operators to a cluster] in the OpenShift documentation for instructions for installing an Operator.


.Additional resources

* See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/metering[Metering] in the OpenShift documentation for more information about installing Metering.
