// Module included in the following assemblies:
//
// assembly-adding-openshift-container-platform-source.adoc
:_module-type: CONCEPT
:experimental:

[id="installation-overview_{context}"]
= Installation tasks summary

[role="_abstract"]
Whether you are replacing a prior {product-title} operator with the *{operator-formal}* or installing it for the first time, the basic tasks are the same.

Operator installation, configuration, and source management can all be performed from the {openshift} web console.

You will perform the following tasks to install the *{operator-formal}* and begin using the {product-title} application in {openshift}.


NOTE: To install and configure {operator-formal} from the {openshift} web console, you must use an account with cluster administrator privileges.

.Prerequisites
- The {openshift} cluster is installed.
- You can access the {openshift} web console using an account that has cluster administrator privileges.


.Task summary
* Install the {operator-formal} (+{operator}+) and use the default token authentication.
* Create a {operator-config} YAML file that configures +{operator}+
* Create a {product-title} {openshift} source with a new installation, or confirm an existing source with a replacement installation.
* After installing the {operator-formal}, delete the old cost operator. This task is required only when a previous {product-title} operator is installed.



If you use Basic authentication, additional steps are required to configure the Secret that holds username and password credentials.
