// Module included in the following assemblies:
//
// assembly_using_cost_models.adoc
// assembly_introduction_cost_management.adoc
// assembly_managing_cost_data_tagging.adoc
// assembly_exporting_cost_data_API.adoc

// * file name: note_tech_preview.adoc
// * ID: [id="note_tech_preview"]
// * Title: = My reference A

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="note_tech_preview_{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.

[NOTE]
====
Cost management is currently Technology Preview. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
