// Module included in the following assemblies:
// assembly_adding_oco_sources.adoc
[id="obtaining_metering_operator_login_ocp"]
[[obtaining_metering_operator_login_ocp]]
== Obtaining Metering Operator login credentials

// The URL for this procedure needs to go in the UI code in the Sources dialog.

During the installation process for the metering operator, the reporting-operator service account is created in the Metering Operator namespace.

. Log in to your OpenShift cluster with an account that has access to the Metering Operator namespace (for example, _metering_).
+
----
# oc login
----
+
. Switch to the _metering_ project:
+
----
# oc project metering
----
+
. Obtain the login token for the reporting-operator service account and copy the token to a file named _ocp_usage_token_:
+
----
# oc serviceaccounts get-token reporting-operator > ocp_usage_token
----
+
[IMPORTANT]
====
As the reporting-operator service account token does not expire, store the token file on a file system with limited access to maintain security. This token is used to obtain metering data on a scheduled basis using a cron job. 
====


