// Module included in the following assemblies:
//
// assembly-planning-your-tagging-strategy.adoc
:_content-type: CONCEPT
:experimental:

[id="planning-tagging-strategy_{context}"]
= Considerations for your tagging strategy

[role="_abstract"]
When planning your tagging strategy, these considerations can help you decide how to organize and report costs for your sources.

Methodology::

It is best practice to implement a Crawl, Walk, Run strategy when initially assigning tags for your resources. Start with the minimum number of tags you feel are required to accomplish your organizational objectives. Then slowly build on that foundation over time. As your understanding of how your organization leverages cost management grows, so will your skill in implementing a tagging strategy.

Map business to reporting::

Define the business perspectives you want to report on. For example, your taxonomy for {product-title} could consider these different perspectives:
+
.Ownership and usage:
Defining the owner and the user of the resource: for example, the unique identifier of the user who requested the resource, and the one that is actually consuming the resource.
+
.Tenancy:
If your environment is shared, it can be beneficial to understand which group or business unit has requested the resource. When the user is part of different groups, one group needs to be selected. For cost reporting, you can achieve this in many cases using cost center; but department, project, or partner are also good candidates.
+
.Location:
For organizations with software deployed globally, cloud providers already identify the region where your resources are running, but your private cloud may be different.
+
.Environment or stage:
You may want to differentiate between development and production, so that different cost decisions can be made depending on the environment where you are creating or running the resources. If your development pipeline already includes stages, such as development, testing, staging, pre-production and production, this is a good candidate.
+
.Application / Project / Service / Event:
Perhaps your environment is providing a service, such as a group of transient resources for an event (for example, your yearly customer-focused conference). You could even include the application version.


Standardize your labels::

Consistency is the most important aspect of a tagging strategy to deliver accurate and comparable cost reporting results.
+
Create a clear tagging policy that defines what resources need to be tagged, what tags are mandatory and what tags are optional, making sure that there is no room for interpretation.
+
If the values need to be chosen between a list, make sure that those values are defined, consistent, and easily accessible, or that the list is presented to the user. For example, if you are defining development with the key “Development”, do not also use variations such as “Dev”, “DEV”, or “R&D” to also identify resources as “Development”.


Tag all elements on your sources (manually or through automation)::

Since untagged resources cannot be reported, tag as many elements as possible, ideally using automation to prevent human error. Sources have different automation features to take advantage of for tagging:

* In Azure, you can use Azure Policies to enforce tagging rules and conventions and avoid resources being deployed that do not comply with your expectations. You can create a policy that automatically applies necessary tags during provisioning, that enforces a predefined format for dates, or that makes some tags mandatory for some resource type.
* In AWS, you can use IAM policies for the same. Additionally, you can use an automation tool such as Ansible to add the necessary tags during provisioning and to make sure that all the resources have been properly tagged.
* OpenShift Container Platform does not presently have a method of automating labelling.

Review your tags often and refine as needed::

Define your tags and use them as early as possible with {product-title}, even if you need to adjust your tagging scheme afterwards.
+
Review the resulting reports with your business owner and stakeholders early on to ensure your tags are helping you to generate the desired reports, and review your tagging strategy every few weeks to optimize it.


Select your tag terminology::

* Name your resources with names that allow you to identify your resources without accessing metadata, and then continue by adding metadata to it. Many clouds have a guide about how to do this properly; see xref:assembly-additional-resources-tags[] for links.
* Map your resources into keys and values. Keys will map to perspectives, while values will define the different options allowed for each key. In some cases, the value will be _Null_.

[NOTE]
====
Not all sources allow the same identifiers, and have different limitations. See xref:tagging-specifications_additional-resources-tags[] for limitations by source.
====
