// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


[id="proc_installing-koku-metrics-operator-on-a-restricted-network_{context}"]
= Installing the Koku Metrics Operator on a restricted network


[role="_abstract"]
For OpenShift Container Platform clusters that are installed on restricted networks, Operator Lifecycle Manager (OLM) by default cannot access the koku-metrics-operator hosted remotely because those remote sources require full Internet connectivity. Therefore, OLM must be configured to install and run local sources.

.Prerequisites

* OpenShift Container Platform cluster installed.
* Workstation with unrestricted network access.
* You are logged into the OCP web console with cluster administrator privileges.

.Procedure

. Follow *link:https://docs.openshift.com/container-platform/4.6/operators/admin/olm-restricted-networks.html[Using Operator Lifecycle Manager on restricted networks]* to install the `koku-metrics-operator` into OLM.
+
[NOTE]
====
The `koku-metrics-operator` is found in the `community-operators` Catalog in the `registry.redhat.io/redhat/community-operator-index:latest` Index.

Red Hat recommends pruning unwanted objects from the index before pushing to the mirrored registry. Make sure you keep the the `koku-metrics-operator` package.
====

. Login to the OCP web console and click on the *Operators > OperatorHub* tab.
. Search for and locate *Koku Metrics Operator*.
. Click on the displayed *Koku Metrics Operator* tile.
. If an information panel appears with the *Community Operators* message, click *Continue*.
. When the *Install Operator* window appears, you must select the `koku-metrics-operator` namespace for installation. If the namespace does not yet exist, it is created for you.
. Click on the *Install* button.


.Verification steps

* After a short wait, *Koku Metrics Operator* appears in the *Installed Operators* tab under *Project: all projects* or *Project: koku-metrics-operator*.

[role="_additional-resources"]
.Additional resources

* For more details on the Operator Lifecycle Manager, see link:https://docs.openshift.com/container-platform/4.6/operators/understanding/olm/olm-understanding-olm.html#olm-overview_olm-understanding-olm[What is Operator Lifecycle Manager?]
