// Module included in the following assemblies:
//
// assembly_using_cost_models.adoc

// Base the file name and the ID on the module title. For example:
// * file name: con_cost_model_workflow.adoc
// * ID: [id="con_cost_model_workflow"]
// * Title: = The cost model workflow

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_installation-overview-ocp45"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Installation tasks summary

Whether you are upgrading from a prior cost management operator to the Koku metrics operator or installing it for the first time, the basic tasks are the same.

Cost management installation, configuration, and source management can all be performed from the OCP web console.

You will perform the following tasks to install the `koku-metrics-operator` cost management operator and begin using the cost management application in OCP 4.5 or later.


NOTE: To install and configure cost management from the OCP web console, you must use an account with cluster administrator privileges.

.Prerequisites
- The OCP 4.5 cluster is installed.
- You can access the OpenShift Container Platform web console using an account that has cluster administrator privileges.

.Task summary
* Install the Koku metrics operator (`koku-metrics-operator`) and use the default token authentication.
* Create a KokuMetricsConfig YAML file that configures `koku-metrics-operator`.
* Create a cost metrics source with a new installation, or confirm an existing source with an upgrade installation.
* Deploy the new cost operator source, if needed.
* After upgrading to the Koku metrics operator, delete the old cost operator. This task is not required in a new cost management installation.

If you use Basic authentication, additional steps are required to configure the Secret that holds username and password credentials.
