// Module included in the following assemblies:
//
// assembly_cost_limiting_access_rbac.adoc

// Base the file name and the ID on the module title. For example:
// * file name: proc_adding_role_to_policy_cost.adoc
// * ID: [id="proc_adding_role_to_policy_cost"]
// * Title: = Adding a role to a policy

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_adding_role_to_policy_cost"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Adding a role to a policy

Add a group

Add a role to a policy to manage and limit the scope of information that users can see within cost management.

.Prerequisites

* Any to note? Admin account, user account?

.Procedure

. Click the Settings icon at the top of the screen to open the *User Access Management* area.
. Click the *Groups* tab.
. Click *Add group*.
. In the *Enter group information* screen, enter a name for the new group, and optionally, a description. Click *Next*.
. In the *Set users* screen, enter the Red Hat login (username) to add users to the group, and click *Next*.
// Can you list multiple users? Separated by commas? Is it case-sensitive?
. (Optional) In the *Create policy* screen, 

.. To create a policy, enter a *Name* and *Description* and click *Next*.
.. Select the roles to add to the policy.
//What does this do?

Cost roles are:
Cost Administrator
Cost Cloud Viewer
Cost OpenShift Viewer
Cost Price List Administrator

// what do each do? add a list defining when to use what.

Policies are the permissions set for this group. Groups can have one or more policies. Policies are created for a group, they cannot be shared. You can only create one policy at this time. It is possible to create more for this group at a later time.

. Confirm the details for this role and click *Confirm* to create the group.

Your new group will be listed in the *Groups* tab on the *User Access Management* screen.

? To verify you added the user correctly, log out of the cost management application and log in as a user you added.

.Next steps

* 

