// Module included in the following assemblies:
//
// assembly_cost_limiting_access_rbac.adoc

// Base the file name and the ID on the module title. For example:
// * file name: proc_adding_role_to_policy_cost.adoc
// * ID: [id="proc_adding_role_to_policy_cost"]
// * Title: = Adding a role to a policy

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_adding_role_to_policy_cost"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Adding a role to a group

Add a role to a group to manage and limit the scope of information that users can see within cost management.

.Prerequisites

* You must be an Account Administrator or a member of a group with the _RBAC Administrator_ role to create a role.
// In AWS, an Account Admin? where is the group RBAC Admin - AWS or RH Insights?

.Procedure

. Click the Settings icon at the top of the screen to open the *User Access Management* area.
. Click the *Groups* tab.
. Click *Add group*.
. In the *Enter group information* screen, enter a name for the new group, and optionally, a description. Click *Next*.
. In the *Set users* screen, enter the Red Hat login (username) to add users to the group, and click *Next*.
// Can you list multiple users? Separated by commas? Is it case-sensitive?
. (Optional) In the *Select roles* screen, select one or more role(s) to add to the group.
+
Default roles available for cost management are:
+
* _Cost Administrator_
* _Cost Cloud Viewer_
* _Cost OpenShift Viewer_
* _Cost Price List Administrator_
+
. Review the details for this group and click *Confirm* to create the group.

Your new group will be listed in the *Groups* tab on the *User Access Management* screen.

To verify your configuration, log out of the cost management application and log back in as a user added to the group.

