// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: proc_creating_an_AWS_cost_model.adoc
// * ID: [id="proc_creating_an_AWS_cost_model"]
// * Title: = Creating an AWS cost model

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_creating_an_AWS_cost_model"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Creating an AWS cost model
// Start the title of a procedure module with a verb, such as Creating or Create. See also _Wording of headings_ in _The IBM Style Guide_.

Since Amazon AWS cost and usage data is collected into Cost Management with prices already assigned, you only need to assign a markup or discount (if desired) for your AWS sources.

.Prerequisites

//edit
* A bulleted list of conditions that must be satisfied before the user starts following this module.
* You can also link to other modules or assemblies the user must follow before starting this module.
* Delete the section title and bullets if the module has no prerequisites.

.Procedure

. From the Cost models menu item (left hand menu), click Create cost model to open the cost model wizard.
. Enter a name and description for the cost model, and select OpenShift Container Platform as the source type to apply the cost model to. Click Next.
. Set a price list to allow you to assign a rate to usage or requests. Cost Management collects these metrics from OpenShift but there is no cost attached to them in Cost Management.
.. Select a metric to apply a value to and click Next.
.. Select a measurement.
.. Enter a rate and save it.
.. Add another rate by repeating the previous steps, or click Next to set a markup.
. Enter a percentage value to apply a markup to the costs, and click Next. 
.. To apply a discount instead of a markup, enter a minus sign with the value (for example, -15). 
.. If you don’t want to apply a markup or discount, enter 0.
+
[NOTE]
====
You can use a markup to account for your overhead costs, such as the cost of administering the cluster, or support costs, for example. A markup is an estimation to cover your costs not shown by metrics or usage.
====
+
. Select one or multiple sources to assign the cost model to and click Next. Selecting a source with a cost model already assigned will override its previous cost model. 
. Review the cost model details, and click Finish to create it.



//.Verification steps
//Now what? What is the result of this, or how can you see this has been applied? → add a verification step and a next step

.Next steps

//add link to tagging doc
Review your tags and tagging strategy to ensure that costs are being distributed to the correct resources, cost centers, or teams. See link:Using tagging to manage cost data for more information.



