// Module included in the following assemblies:
//
// assembly-setting-up-cost-models.adoc

[id="proc-creating-an-aws-azure-cost-model_{context}"]

= Creating an Azure cost model

Since Microsoft Azure cost and usage data is collected into cost management with prices already assigned, you only need to assign a markup or discount (if desired) for your Azure sources.

//.Prerequisites


.Procedure

. From the *Cost models* menu, click btn:[Create cost model] to open the cost model wizard.
. Enter a name and description for the cost model, and select *Microsoft Azure* as the source type to apply the cost model to. Click btn:[Next].
. To apply a markup to the base costs of your resources, enter a percentage value and click btn:[Next].
* To apply a discount rather than a markup, enter a minus sign with the value (for example, _-15_).
* If you do not want to apply a markup or discount, enter _0_.
+
[NOTE]
====
You can use a markup to account for your overhead costs, such as the cost of administering the cluster, or support costs, for example. A markup is an estimation to cover your costs not shown by metrics or usage.
====
+
. Optionally, select one or multiple sources to assign the cost model to and click btn:[Next]. Selecting a source with a cost model already assigned will override its previous cost model. You can also assign sources to your cost model at a later time.
. Review the cost model details, and click btn:[Create].
. Click btn:[Close] to exit the cost model wizard.

Your new cost model will appear in the list on the *Cost models* page.

.Next steps

* From the *Cost models* page, click the more options button to *View details* or *Delete* the cost model. From the *View details* option, you can edit the cost model, including source assignments, markup, and more settings.

* Review your tags and tagging strategy to ensure that costs are being distributed to the correct resources, cost centers, or teams. See link:https://access.redhat.com/documentation/en-us/cost_management_service/2021/html-single/managing_cost_data_using_tagging/index[_Managing cost data using tagging_] for more information.
