// Module included in the following assemblies:
// assembly_adding_oco_sources.adoc
[id="proc_obtaining_operator_metering_login"]
=== Obtaining Operator Metering login credentials

// The URL for this procedure needs to go in the UI code in the Sources dialog - need to give to Dan & Boaz.


During the installation process for Operator Metering, the metering-operator service account is created in the Operator Metering namespace. 

. Log in to your OpenShift cluster with an account that has access to the Operator Metering namespace (e.g. _metering_).
+
----
# oc login
# oc project metering
----
+
. Obtain the login token for the metering-operator service account and copy the token into a file named _ocp_usage_token_:
+
----
# oc serviceaccounts get-token metering-operator > ocp_usage_token
----
+
[IMPORTANT]
====
As the metering-operator service account token does not expire, store the token file on a file system with limited access to maintain security. This token is used to obtain metering data on a scheduled basis using a cron job.
Cost Management requires an Amazon S3 bucket with permissions configured to store billing reports.
====


