
[id="proc_basic-authentication"]
= Configuring basic authentication for cost operator

You can configure the cost operator to use basic authentication. By default, the cost operator uses token authentication.

There are two procedures required when you configure basic authentication.

* xref:creating-secret-pair[Creating the secret key/value pair for basic authentication]
* xref:modify-yaml-file[Modifying the YAML file]

[id="creating-secret-pair"]
[[creating-secret-pair]]
== Creating the secret key/value pair for basic authentication

.Prerequisites
* You are logged into the OCP web console with cluster administrator privileges.
* The *Koku Metrics Operator* appears in the *Installed Operators* tab.
* You have a username and password for your https://cloud.redhat.com[cloud.redhat.com] account.


.Procedure
This procedure describes setting up basic authentication using the OCP web console.

. In the OCP web console, click on the *Workloads > Secrets* tab.
. In the *Secrets* window, select *Project:koku-metrics-operator* from the dropdown.
. Click the *Create > Key/Value Secret* selection.
. In the *Create Key/Value Secret* window enter the following information to create a new secret that contains a username key and a password key and a value for each key.
.. Enter a name for your secret in the *Secret Name* field.
+
.Secret name example
----
basic-auth-secret
----
.. In the *Key* field, enter `username`. This is your first key of the key pair.
+
.Key name example for username
----
username
----
.. In the *Value* field for the username key, enter the actual username for your authorized https://cloud.redhat.com[cloud.redhat.com] user account.
+
.Key value example for username
----
RedHatUser
----
.. Click the `Add Key/Value` link to add the required password key name and value.
.. In the *Key* field, enter `password`. This is your second key of the key pair.
+
.Key name example for password
----
password
----
.. In the *Value* field for the password key, enter the actual password for your authorized https://cloud.redhat.com[cloud.redhat.com] user account.
+
.Key value example for password
----
my.User!password
----
.. Click the *Create* button to complete the creation of your basic authorization secret.
.. After you click the *Create* button, you can verify the key information details for the secret.
+
NOTE: Do _not_ add the secret to the workload.

[id="modify-yaml-file"]
[[modify-yaml-file]]
== Modifying the YAML file

Modify the Koku metrics operator API YAML file to use basic authentication with a secret username and password key/value pair.


.Prerequisites
* You are logged into the OCP web console with cluster administrator privileges.
* You created a secret name for the username and password key/value pair.
* The Koku metrics operator is installed.

.Procedure

. Click on the *Operators > Installed Operators* tab.
. Locate the row that contains *KokuMetricsOperator* and click on the *KokuMetricsConfig* link that is under the *Provided APIs* heading.
. When the *KokuMetricsConfigs* window appears, click on Koku configuration file listed in the *Name* column.
+
The default name is *kokumetricscfg-sample*.
. When the *kokumetricscfg-sample* window appears, click in the *YAML* tab to open an edit and view window.
. Locate the following lines in the YAML view.
+
----
  authentication:
    type: token
----
. Change `type: token` to `type: basic`.
. Insert a new line for `secret_name`. Enter the value for  `secret_name`, which is the name you previously created.
+
.Example
----
  authentication:
    secret_name: basic-auth-secret
    type: basic
----
. Click the *Save* button. A confirmation message appears.
