// Module included in the following assemblies:
//
// assembly_cost_limiting_access_rbac.adoc

// Base the file name and the ID on the module title. For example:
// * file name: proc_creating_a_role_cost.adoc
// * ID: [id="proc_creating_a_role_cost"]
// * Title: = Creating a role

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="proc_creating_a_role_cost"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Adding a role

Create a new role to manage and limit the scope of information that users can see within cost management.

.Prerequisites

* Any to note? Admin account, user account?

.Procedure

. Click the Settings icon at the top of the screen to open the *User Access Management* area.
. Click the *Roles* tab.
. Click *Add Role* to open the *Add role* wizard.
. In the *Name and Description* screen, enter a name for the new role, and optionally, a description. Click *Next*.
. In the *Permission* screen, specify the Red Hat Cloud Services application you are creating the role for (in this case, cost management) as well as the resource and permission type:
.. For *Application*, enter _cost-management_.
//UI note -- this should be a drop-down for ease of use.
.. For *Resource type*, specify the resource this permission will be used to access from the following list:
+
- _group_
- _role_
- _policy_
- _aws.account_
- _openshift.cluster_
+
.. For *Permission*, specify whether this role can write to the resource (which includes read access), or is read-only, by entering _write_ or _read_.
+
For example, to create a role with read-only permissions to AWS account data, set _aws.account_ as the *Resource type* and _read_ as the *Permission*. In the next step, you can specify the AWS account to apply this role to.
+
. (Optional) In the *Resource definitions* screen, you can provide more details about the resources the permission will be used for. For example, to configure this for ???, enter the following and click *Add to definitions*:
* *Key*: _aws.account_
* *Operation*: _equal_
* *Value*: Your AWS account number or account alias.
+
[NOTE]
====
The following options are available for the Resource definitions step:
* *Key* : - _group_, _role_, _policy_, _aws.account_, _openshift.cluster_
* *Operation*: Use _equal_ if you know the exact value, or _list_ to see a list of values that will work for this role.
* *Value*: 
====
+
You see a list of values that will work for this role
- giving these permissions to these things.
. Confirm the details for this role and click *Confirm* to create the role.

Your new role will be listed in the *Roles* tab on the *User Access Management* screen.

.Next steps

* Add your role to new policies that you create for new groups.


