[preface]
[id="proc-providing-feedback-on-redhat-documentation"]
= Providing feedback on Red Hat Cost Management documentation

We appreciate your feedback on our documentation.
To provide feedback, highlight text in a document and add comments.

.Prerequisites

* You are logged in to the Red Hat Customer Portal.
* In the Red Hat Customer Portal, the document is in the *Multi-page HTML* viewing format.

.Procedure

To provide your feedback, perform the following steps:

. Click the *Feedback* button in the top-right corner of the document to see existing feedback.
+
NOTE: The feedback feature is enabled only in the *Multi-page HTML* format.

. Highlight the section of the document where you want to provide feedback.

. Click the *Add Feedback* pop-up that appears near the highlighted text.
+
A text box appears in the feedback section on the right side of the page.

. Enter your feedback in the text box and click *Submit*.
+
A documentation issue is created.

. To view the issue, click the issue link in the feedback view.
