// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: my-reference-a.adoc
// * ID: [id="my-reference-a"]
// * Title: = My reference A

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="reference-material_{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Cost model terminology
//In the title of a reference module, include nouns that are used in the body text. For example, "Keyboard shortcuts for ___" or "Command options for ___." This helps readers and search engines find the information quickly.

These terms and concepts are important for understanding Cost Management’s cost model
workflow.

Cost model:: A framework used to define the calculations for the costs stored in Cost Management, using base
costs and metrics. The cost model is used for budgeting and accounting, and also the visualization
and analysis of costs— in Cost Management it provides the basis for the cost information that the
user will view. Costs generated by a cost model can be recorded, categorized and allocated to
specific customers, business units or projects.
Raw metrics and costs:: Raw metrics and costs are the metrics and costs provided by a third party that have not been
modified in any way, such as the AWS costs provided by the AWS Cost and Usage Report files or the
API, and the OpenShift metrics provided through Operator Metering.
Base costs:: Base costs originate from different sources, such as metrics, inventory, or reports, which are
normalized so a markup can be applied. Base costs can be calculated directly in the Cost
Management application by applying a price list to metrics or inventory, or they can be calculated
externally (i.e. AWS provided costs). In the Cost Management application’s cost model, a markup is
applied to base costs to get calculated costs.
Price list:: A price list is a list of rates used within the application’s cost model to calculate the base cost of
resources.
Markup:: In the Cost Management application, the markup is the ratio, positive or negative, between the base
cost and the calculated cost.
Calculated costs:: Calculated costs are the costs stored in the application after a markup is added to the base costs.
Distributed costs:: Calculated costs become distributed costs once they are associated to higher level application
concepts, such as user, team, project, account, service, and so on.

