// Module included in the following assemblies:
//
// assembly_using_cost_models.adoc

// Base the file name and the ID on the module title. For example:
// * file name: ref_cost_model_terms.adoc
// * ID: [id="ref_cost_model_terms"]
// * Title: = Cost model terminology

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="ref_cost_model_terms"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Cost model concepts

These terms and concepts are important for understanding cost management’s cost model workflow.

Cost model:: A cost model is a framework used to define the calculations for the costs stored in cost management, using raw costs and metrics. The cost model is used for budgeting and accounting, and also the visualization and analysis of costs — in cost management it provides the basis for the cost information that the user will view. Costs generated by a cost model can be recorded, categorized and allocated to
specific customers, business units or projects.

== Cost types

All costs can be classified as either infrastructure or supplementary costs. In your cost model, you can specify how you want to allocate these cost types. As a result, you can customize what cost management shows on each details page view.

Infrastructure cost:: This cost can come from two different sources:
* Costs directly reported by a cloud provider, via an AWS Cost and Usage report or Azure billing report.
* Costs calculated from a cost model price list for rates specifically marked as infrastructure (e.g. node/cluster cost per month rates by default)

Supplementary cost:: All cost not directly attributed to infrastructure. These costs come from applying a cost model price list to metrics obtained from an OpenShift cluster. The rates in the price list must be specified as supplementary This is the default for everything except node/cluster cost per month rates. 


== Cost model terminology

Cost:: This is the sum of infrastructure and supplementary costs. This can be thought of as “total cost” for the filtered slice of data being shown (for example. cost for a particular account, region, or service).

Raw cost:: These are the costs reported by a cloud provider without any cost model calculations applied.

//Previously: Raw metrics and costs:: Raw metrics and costs are the metrics and costs provided by a third party that have not been modified in any way, such as the AWS costs provided by the AWS Cost and Usage Report files or the API, and the OpenShift metrics provided through Operator Metering.

Markup:: This is the portion of cost calculated by applying markup or discount to raw cost in the cost management application.
+
_Example: For a raw cost of $100 and a markup of 10%, the returned value would be $10, the cost would be $110 (sum of both)._

// Previously: In the cost management application, the markup is the ratio, positive or negative, between the base cost and the calculated cost.

Usage cost:: This is the portion of cost calculated by applying hourly and/or monthly price list rates to metrics.
+
_Example: For a metric of 100 core-hours and a rate of $1/core-hour the returned value (usage cost) would be $100._

//Previously:  Base costs:: Base costs originate from different sources, such as metrics, inventory, or reports, which are normalized so a markup can be applied. Base costs can be calculated directly in the cost management application by applying a price list to metrics or inventory, or they can be calculated externally (for example, AWS provided costs). In the cost management application’s cost model, a markup is applied to base costs to get calculated costs.

//Do we need this term?
Monthly cost:: This is the portion of cost calculated by applying monthly price list rates to metrics. It is returned as part of usage cost.
Note: These costs are not currently amortized over reported period in the API, so when viewing a daily breakdown of cost, monthly costs will only show on the 1st of the month. 
+
_Example: For an OpenShift cluster with 10 nodes and a rate of $10,000/node/month the returned value would be $100,000._

Price list:: A price list is a list of rates used within the application’s cost model to calculate the usage cost of resources.

//Do we still have 'calculated costs?'
Calculated costs:: Calculated costs are the costs stored in the application after a markup is added to the usage costs.

Distributed costs:: Calculated costs become distributed costs once they are associated to higher level application concepts, such as user, team, project, account, service, and so on.




