// Module included in the following assemblies:
//
// assembly-adding-openshift-container-platform-source.adoc
:_content-type: PROCEDURE
:experimental:

[id="removing-a-cost-operator_{context}"]
= Removing a prior cost operator

[role="_abstract"]
After installing the +{operator}+, uninstall the prior {product-title} operator.

To avoid gaps in your {product-title} data, you can wait 24 to 48 hours before removing the prior operator while you verify that +{operator}+ provides {product-title} reports.

NOTE: If you mistakenly remove the *{operator-formal}*, reinstall it.

.Prerequisites
* A prior {product-title} operator is installed.
* You installed the *{operator-formal}*.
* You are logged into the {openshift} web console with cluster administrator privileges.
* You can view the operators in the *Installed Operators* tab.

.Procedure
. In the Installed Operators list, select the operator you want to remove.
. Click the *Options* menu {kebab} in that row.
. Click on the *Uninstall Operator* option. Confirm the action to remove the operator.
. In the {openshift} web console, click the *Administration > Custom Resource Definitions* tab.
. In the window that displays the custom resource definitions (CRD), locate the *CostManagement* CRD and the *CostManagementData* CRD for `cost-mgmt-operator` or the *KokuMetricsConfig* CRD for `koku-metrics-operator`.
. For each CRD, click the *Options* menu {kebab} -> *Delete Custom Resource Definition*. Confirm the delete action.
. When these CRDs are deleted, the prior operator is fully uninstalled.

NOTE: When you install *{operator-formal}*, a *{operator-config}* CRD appears in  *Administration > Custom Resource Definitions* list.
