// Module included in the following assemblies:
//
// assembly_managing_cost_data_tagging.adoc

// Base the file name and the ID on the module title. For example:
// * file name: viewing_cost_data_tag_category.adoc
// * ID: [id="viewing_cost_data_tag_category"]
// * Title: = Viewing cost data by tag category

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id="viewing_cost_data_tag_category{context}"]
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Viewing cost data by tag category
// Start the title of a procedure module with a verb, such as Creating or Create. See also _Wording of headings_ in _The IBM Style Guide_.

Tags allow you to customize your view of cost data. You can group resources by tag in order to to investigate why certain resources show an increase in cost, or data looks abnormal.

This example shows how to see OpenShift ???

.Prerequisites

* Configure tags on your sources. For tips and configuration instructions, see LINK.

.Procedure

. From the *OpenShift details* menu, click the filter button and select *Tag*.
. In the *Choose key* dropdown list, select the key to filter by. For example, select _version_. Selecting a tag key reveals another dropdown to choose the value to filter by.
. In the *Choose value* dropdown list, select one or more values to filter by. For example, select _qe_ and _dev_ to show cost data for OpenShift resources with these tags.
//Is that right? How can this be more useful?
. To view more information about each resource:
* Click the more options icon (ICON) to reveal more view options:
** Click *View historical data* to open the daily usage comparison view, which compares usage, request, and limits by day between months for that resource.
** Click *Export data* to create a .csv file for for reporting. Specify a daily or monthly aggregate and click *Generate and download*.
* Click the arrow (ICON) at the left of each resource to expand the details and see information such as the cluster(s) the resource belongs to, and CPU and memory usage, limits, and requests.
* Click *View Historical Data* to open the daily usage comparison view, which compares usage, request, and limits by day between months for that resource.
. Click *Clear all filters* to reset your OpenShift details view.



//.Additional resources

//* A bulleted list of links to other material closely related to the contents of the procedure module.

