// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>
:_module-type: PROCEDURE
:experimental:

[id="viewing-data-export-requests_{context}"]
= Viewing previous data export requests

[role="_abstract"]
You can use the API to list previous data export requests to prevent duplicating data. This also checks if the user has requested the same data multiple times before the request has completed.

Most data export requests complete in a few seconds, however, this can be useful for troubleshooting processing delays or other issues.

.Procedure

. To retrieve a list of all data export requests that were created by the authenticated user, run a GET request with the URL `/api/cost-management/v1/dataexportrequests/`:
+
----
HTTP GET localhost:8000/api/cost-management/v1/dataexportrequests/
----
+
For example, using `curl`, run:
+
----
$  curl -s -u "$MYUSER:$MYPASS" -F start_date='2019-11-01' -F end_date='2019-11-10' -F bucket_name='koku-customer-sample-bucket' localhost:8000/api/cost-management/v1/dataexportrequests/ | jq
{
 "uuid": "8c619402-3cf9-4b19-a01b-9942d0cd6c1b",
 "created_timestamp": "2019-11-26T19:35:13.437243Z",
 "updated_timestamp": "2019-11-26T19:35:13.437275Z",
 "start_date": "2019-11-01",
 "end_date": "2019-11-10",
 "status": "pending",
 "bucket_name": "koku-customer-sample-bucket"
}
----
+
The response provides the request UUID, and shows the request is still in progress.
+
. To retrieve a requested data export request by UUID (assuming it is reachable by the authenticated user), run a GET request with the URL `/api/cost-management/v1/dataexportrequests/{uuid}/`, using the request UUID:
+
----
HTTP GET localhost:8000/api/cost-management/v1/dataexportrequests/{uuid}/
----
+
For example, using `curl`, run:
+
----
$  curl -s -u "$MYUSER:$MYPASS" localhost:8000/api/cost-management/v1/dataexportrequests/8c619402-3cf9-4b19-a01b-994
2d0cd6c1b/ | jq -C
{
 "uuid": "8c619402-3cf9-4b19-a01b-9942d0cd6c1b",
 "created_timestamp": "2019-11-26T19:35:13.437243Z",
 "updated_timestamp": "2019-11-26T19:35:25.232298Z",
 "start_date": "2019-11-01",
 "end_date": "2019-11-10",
 "status": "complete",
 "bucket_name": "koku-customer-sample-bucket"
}
----

The response shows the request status is complete.
