sudo: required

services:
  - docker

before_install:
  - echo 2994f2c9-3523-4968-a7d4-ad08aa3a4821 | docker login -u junixon --password-stdin
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $(pwd):/documents/ --name getting-started asciidoctor/docker-asciidoctor asciidoctor downstream/titles/getting_started/master.adoc
  - docker run -v $(pwd):/documents/ --name cost-models asciidoctor/docker-asciidoctor asciidoctor downstream/titles/using_cost_models/master.adoc
  - docker run -v $(pwd):/documents/ --name using-tags asciidoctor/docker-asciidoctor asciidoctor downstream/titles/managing_cost_data_using_tags/master.adoc

after_error:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags

after_failure:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags

after_success:
  - sudo git clone https://github.com/project-koku/koku-doc.git -b gh-pages output
  - cd output ; sudo mv ../downstream/titles/using_cost_models/master.html cost-models.html ; sudo mv ../downstream/titles/getting_started/master.html getting-started.html ; sudo mv ../downstream/titles/managing_cost_data_using_tags/master.html using-tags.html ; sudo cp -R ../downstream/images images
  - sudo git config user.name "${GH_USER_NAME}"
  - sudo git config user.email "{GH_USER_EMAIL}"
  - sudo git add .
  - sudo git commit -m "Deploy ${TRAVIS_COMMIT_RANGE} to github pages"
  - sudo git push --force --quiet "https://${GH_TOKEN}@github.com/project-koku/koku-doc.git" gh-pages > /dev/null 2>&1
