sudo: required

services:
  - docker

before_install:
 # - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $(pwd):/documents/ --name getting-started asciidoctor/docker-asciidoctor asciidoctor downstream/titles/getting_started/master.adoc
  - docker run -v $(pwd):/documents/ --name cost-models asciidoctor/docker-asciidoctor asciidoctor downstream/titles/using_cost_models/master.adoc
  - docker run -v $(pwd):/documents/ --name using-tags asciidoctor/docker-asciidoctor asciidoctor downstream/titles/managing_cost_data_using_tags/master.adoc

after_error:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags

after_failure:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags

#after_success:
# - cd output ; sudo mv master.html index.html;
#  - sudo git init
#  - sudo git config user.name "${GH_USER_NAME}"
#  - sudo git config user.email "{GH_USER_EMAIL}"
#  - sudo git add . ; sudo git commit -m "Deploy to GitHub Pages"
#  - test $TRAVIS_BRANCH = "master" && sudo git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
