sudo: required

services:
  - docker

before_install:
  - echo ${DKR_TKN} | docker login -u ${DKR_USR} --password-stdin
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $(pwd):/documents/ --name getting-started asciidoctor/docker-asciidoctor asciidoctor downstream/titles/getting_started/master.adoc
  - docker run -v $(pwd):/documents/ --name cost-models asciidoctor/docker-asciidoctor asciidoctor downstream/titles/using_cost_models/master.adoc
  - docker run -v $(pwd):/documents/ --name using-tags asciidoctor/docker-asciidoctor asciidoctor downstream/titles/managing_cost_data_using_tags/master.adoc
  - docker run -v $(pwd):/documents/ --name aws-source asciidoctor/docker-asciidoctor asciidoctor downstream/titles/adding_aws_source/master.adoc
  - docker run -v $(pwd):/documents/ --name azure-source asciidoctor/docker-asciidoctor asciidoctor downstream/titles/adding_azure_source/master.adoc
  - docker run -v $(pwd):/documents/ --name gcp-source asciidoctor/docker-asciidoctor asciidoctor downstream/titles/adding_gcp_source/master.adoc
  - docker run -v $(pwd):/documents/ --name ocp-source asciidoctor/docker-asciidoctor asciidoctor downstream/titles/adding_ocp_source/master.adoc

after_error:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags
  - docker logs aws-source
  - docker logs azure-source
  - docker logs gcp-source
  - docker logs ocp-source

after_failure:
  - docker logs getting-started
  - docker logs cost-models
  - docker logs using-tags
  - docker logs aws-source
  - docker logs azure-source
  - docker logs gcp-source
  - docker logs ocp-source

if: branch = main
after_success:
 - sudo git clone https://github.com/project-koku/koku-doc.git -b gh-pages output
 - cd output ; sudo mv ../downstream/titles/using_cost_models/master.html cost-models.html ; sudo mv ../downstream/titles/getting_started/master.html getting-started.html ; sudo mv ../downstream/titles/managing_cost_data_using_tags/master.html using-tags.html ; sudo mv ../downstream/titles/adding_aws_source/master.html aws-source.html ; sudo mv ../downstream/titles/adding_azure_source/master.html azure-source.html ; sudo mv ../downstream/titles/adding_gcp_source/master.html gcp-source.html ; sudo mv ../downstream/titles/adding_ocp_source/master.html ocp-source.html ; sudo cp -a ../downstream/images/. images
  - sudo git config user.name "${GH_USER_NAME}"
  - sudo git config user.email "{GH_USER_EMAIL}"
  - sudo git add .
  - sudo git commit -m "Deploy ${TRAVIS_COMMIT_RANGE} to github pages"
  - sudo git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1