= How to contribute to this repository

== About this project

Koku is the upstream project for Red Hat Cost Management.
We welcome all contributors!

This repository contains documentation written in AsciiDoc. For more information on AsciiDoc markup and syntax, see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/.

To test build the documentation, use Asciidoctor. For more information on installing and using Asciidoctor, see https://asciidoctor.org/.


== Modular documentation structure

The following is a map of this repository:

....
.
|
├── community
├── downstream
│   ├── attributes
|   ├── assemblies
│   │   ├── assembly-title-1.adoc
│   │   ├── assembly-title-2.adoc
│   │   └── modules -> ../modules/
│   ├── images
│   │   ├── image-1.png
│   │   └── image-2.png
│   ├── modules
│   │   ├── module-title-1.adoc
│   │   └── module-title-2.adoc
|   └── titles
│
└── README.adoc
....

Top-level directories are:

* community: A directory for upstream-specific assemblies and titles.
* downstream: A directory that stores modules, assemblies, and titles relevant to both downstream and upstream. 

Lower-level directories are:

* attributes: A common directory for attribute files. 
* assemblies: A directory for all assemblies, each on in its own AsciiDoc tile. Assemblies are collections of modules linked together. 
* images: A directory for all images and other digital content.
* modules: A directory for all modules, each one in its own AsciiDoc file.
* titles: A directory for titles, which are collections of assemblies linked together.

=== Modules

Modules are categorized by content type and written using templates.

Modules can be procedure, concept, or reference topics. The module type is labelled in each file name:

* Procedure: `_TOPIC.adoc`
* Concept: `_con_TOPIC.adoc`
* Reference: `_ref_TOPIC.adoc`

Templates are available in this repository's _modules_ directory to copy and write from.

See the _Modular Documentation Reference Guide_ for information about these file types: https://redhat-documentation.github.io/modular-docs/.


=== Conventions

Images::
* UI icons, if needed, should be approximately 21px x 21px in size and saved in the _Images_ directory.


