// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-cost-management-next-steps: {context}]

ifndef::context[]
[id="assembly-cost-management-next-steps"]
endif::[]
ifdef::context[]
[id="assembly-cost-management-next-steps_{context}"]
endif::[]

= Next steps for managing your costs
:context: next-steps

[role="_abstract"]
After adding your infrastructure and cloud sources, in addition to showing cost data by source, {product-title} will automatically show AWS, Google Cloud, and Azure cost and usage related to running your OpenShift Container Platform clusters on their platforms.

On the {product-title} *Overview* page ({link-cost-management}), your cost data will be sorted into *OpenShift* and *Infrastructure* tabs. From here, you can use *Perspective* to select different views of your cost data.

You can also use the left navigation menu to view the additional details of your costs by service.

include::../modules/configure-tagging-next-step.adoc[leveloffset=+1]

include::../modules/configure-cost-models-next-step.adoc[leveloffset=+1]

include::../modules/cost-explorer-next-step.adoc[leveloffset=+1]

// Restore the context to what it was before this assembly.
ifdef::parent-context-of-assembly-cost-management-next-steps[:context: {parent-context-of-assembly-cost-management-next-steps}]
ifndef::parent-context-of-assembly-cost-management-next-steps[:!context:]
