// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-adding-aws-sources: {context}]

ifndef::context[]
[id="assembly-adding-aws-sources"]
endif::[]
ifdef::context[]
[id="assembly-adding-aws-sources_{context}"]
endif::[]

= Adding an Amazon Web Services (AWS) source to {product-title}
:context: adding-aws-sources

[role="_abstract"]
To add an AWS account to {product-title}, you must configure your AWS account to provide metrics, then add your AWS account as a source from the {product-title} user interface.

[NOTE]
====
You must have a Red Hat account user with Sources Administrator entitlements before you can add sources to {product-title}.
====

When you add your AWS account as a source, this creates a read-only connection to AWS in order to collect cost information hourly in {product-title}, but does not make any changes to the AWS account.

// [IMPORTANT]
// ====
// You must use an AWS master account for this procedure, as a linked AWS account does not have sufficient access to create billing // accounts. After you add the master account as a source, {product-title} will collect data from any linked accounts as well.
// ====
Before you can add your AWS account to {product-title} as a data source, you must configure the following services on your AWS account to allow {product-title} access to metrics:

. An S3 bucket to store cost and usage data reporting for {product-title}
. An Identity Access Management (IAM) policy and role for {product-title} to process the cost and usage data

As you will complete some of the following steps in the AWS console, and some steps in the {product-title} user interface, keep both applications open in a web browser.

Add your AWS source to {product-title} from the settings area at
https://cloud.redhat.com/settings/sources/.

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the link:https://docs.aws.amazon.com/[AWS documentation] for the most up-to-date and accurate information.
====

include::../modules/creating-an-aws-s3-bucket.adoc[leveloffset=+1]

include::../modules/activating-aws-tags.adoc[leveloffset=+1]

include::../modules/enabling-aws-account-access.adoc[leveloffset=+1]

include::../modules/enabling-additional-aws-account-access.adoc[leveloffset=+1]

You have completed adding your AWS account as a source.

// Restore the context to what it was before this assembly.
ifdef::parent-context-of-assembly-adding-aws-sources[:context: {parent-context-of-assembly-adding-aws-sources}]
ifndef::parent-context-of-assembly-adding-aws-sources[:!context:]
