// This assembly is included in the following assemblies:
//
// master.adoc

// Retains the context of the parent assembly if this assembly is nested within another assembly.
// For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
// See also the complementary step on the last line of this file.
ifdef::context[:parent-context: {context}]

// Base the file name and the ID on the assembly title. For example:
// * file name: assembly_limiting_access_cost_resources_rbac.adoc
// * ID: [id="assembly_limiting_access_cost_resources_rbac"]
// * Title: = Limiting access to cost management resources

[id="assembly_limiting_access_cost_resources_rbac"]
// If the assembly is reused in other assemblies in a guide, include {context} in the ID: [id="a-collection-of-modules_{context}"].
= Limiting access to cost management resources
//:context: assembly-keyword
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.

You may not want users to have access to all cost data, but instead only data specific to their projects or organization. Using role-based access control, you can limit the visibility of resources involved in cost management reports. For example, you may want to restrict a user's view to only AWS sources, instead of the entire environment.

Role-based access control works by organizing users into groups, which can be associated with one or more roles. A role defines a permission and a set of resource definitions.

By default, a user who is not an account administrator will not have access to data, but instead must be granted access to resources. Account administrators can view all data without any further role-based access control configuration.


[NOTE]
====
A Red Hat account user with Organization Administrator entitlements is required to configure Red Hat account users. This Red Hat login allows you to look up users, add them to groups, and to assign roles that control visibility to resources.

For more information about Red Hat account roles, see https://access.redhat.com/articles/1757953[Roles and Permissions for Red Hat Subscription Management] and https://access.redhat.com/start/how-to-create-and-manage-users[How To Create and Manage Users].
====

== Default user roles in cost management

You can configure custom user access roles for cost management, or assign each user a predefined role.

To use a default role, determine the required level of access to permit your users based on the following predefined roles in cost management:

.Administrator roles

* Cost Administrator:  has read and write permissions to all resources in cost management
* Cost Price List Administrator:  has read and write permissions on price list rates

.Viewer roles

* Cost Cloud Viewer:  has read permissions on cost reports related to cloud sources
* Cost OpenShift Viewer:  has read permissions on cost reports related to OpenShift sources
* Cost Price List Viewer:  has read permissions on price list rates


include::../modules/adding_a_role_cost_rbac.adoc[leveloffset=+1]

include::../modules/adding_role_to_group_cost_rbac.adoc[leveloffset=+1]

/////
// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
/////
