// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-adding-gcp-sources: {context}]

ifndef::context[]
[id="assembly-adding-gcp-sources"]
endif::[]
ifdef::context[]
[id="assembly-adding-gcp-sources_{context}"]
endif::[]

= Adding a Google Cloud source to cost management
:context: adding-gcp-sources

[role="_abstract"]
To add a Google Cloud account to cost management, you must configure your Google Cloud to provide metrics, then add your Google Cloud account as a source from the cost management user interface.

[NOTE]
====
You must have a Red Hat account user with Organization Administrator entitlements before you can add sources to cost management.
====

When you add your AWS account as a source, this creates a read-only connection to AWS in order to collect cost information hourly in cost management, but does not make any changes to the AWS account.

[IMPORTANT]
====
You must use an AWS master account for this procedure, as a linked AWS account does not have sufficient access to create billing accounts. After you add the master account as a source, cost management will collect data from any linked accounts as well.
====

Before you can add your AWS account to cost management as a data source, you must configure the following services on your AWS account to allow cost management access to metrics:

. An S3 bucket to store cost and usage data reporting for cost management
. An Identity Access Management (IAM) policy and role for cost management to process the cost and usage data

As you will complete some of the following steps in the Google Cloud console, and some steps in the cost management user interface, keep both applications open in a web browser.

Add your AWS source to cost management from the settings area at
https://cloud.redhat.com/settings/sources/.

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the link:gcpdocumentation for the most up-to-date and accurate information.
====

////
Restore the context to what it was before this assembly.
////
ifdef::parent-context-of-assembly-adding-gcp-sources[:context: {parent-context-of-assembly-adding-gcp-sources}]
ifndef::parent-context-of-assembly-adding-gcp-sources[:!context:]
