// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-adding-ocp-sources: {context}]

ifndef::context[]
[id="assembly-adding-ocp-sources"]
endif::[]
ifdef::context[]
[id="assembly-adding-ocp-sources_{context}"]
endif::[]

= Adding an OpenShift Container Platform 4.3 and 4.4 source to {product-title}
:context: adding-previous-source

[NOTE]
====
Use these instructions with OpenShift Container Platform 4.3 or 4.4 for use with the `cost-mgmt-operator` operator. This operator is deprecated for OpenShift Container Platform 4.5 and later.

For OCP 4.5 and later, see xref:assembly-adding-openshift-container-platform-source[].
====

[role="_abstract"]
To add an OpenShift Container Platform cluster as a source to {product-title}, you must first configure your cluster to provide usage data (metrics) using the {product-title} Operator.

[NOTE]
====
You must have a Red Hat account user with Sources Administrator entitlements before you can add sources to {product-title}.
====

The {product-title} Operator (`cost-mgmt-operator`) collects the metrics required for {product-title} by:

* Using Operator Metering to create usage reports specific to {product-title}.
* Collecting and packaging these reports to a tarball which is uploaded to {product-title} through {platform-title}.



To add your OpenShift Container Platform cluster as a {product-title} source:

. Install the {product-title} Operator in OpenShift from OperatorHub
. Configure the {product-title} Operator to collect OpenShift usage data (metrics) using Operator Metering
. Provide the cluster identifier to {product-title}

As you will complete some of the following steps in OpenShift Container Platform, and some steps in the {platform-title} ({link-sources}), have both applications open in a web browser, as well as a terminal to access the command line interface (CLI).



include::../modules/installing-cost-mgmt-operator.adoc[]


include::../modules/configuring-cost-mgmt-operator.adoc[]



{product-title} will begin collecting usage data (metrics) from your OpenShift Container Platform cluster. The data can take a few days to populate before it shows on the {product-title} dashboard.

You have completed adding your OpenShift Container Platform cluster as a source.

// Restore the context to what it was before this assembly.
ifdef::parent-context-of-assembly-adding-ocp-sources[:context: {parent-context-of-assembly-adding-ocp-sources}]
ifndef::parent-context-of-assembly-adding-ocp-sources[:!context:]
