// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-cost-management-next-steps: {context}]

ifndef::context[]
[id="assembly-cost-management-next-steps"]
endif::[]
ifdef::context[]
[id="assembly-cost-management-next-steps_{context}"]
endif::[]

= Next steps for managing your costs
:context: next-steps

[role="_abstract"]
After adding your infrastructure and cloud sources, in addition to showing cost data by source, {product-title} will automatically show AWS, Google Cloud, and Azure cost and usage related to running your OpenShift Container Platform clusters on their platforms.

On the {product-title} *Overview* page, use the *Perspective* options for different views of your cost data.

Use the *Details* menu to look more closely at your costs.

== Configure tagging for your sources

The {product-title} application tracks cloud and infrastructure costs using tags (called labels in OpenShift), which you can refine to filter and attribute to resources. Tags in {product-title} allow you to organize your resources by cost and to allocate the costs to different parts of your cloud infrastructure.

[IMPORTANT]
====
Tags and labels can only be configured directly on a source. You cannot edit tags and labels in the {product-title} application.
====

See _{link-tagging}_ to learn more about:

* Planning your tagging strategy to organize your view of cost data
* Understanding how {product-title} associates tags
* Configuring tags and labels on your sources



== Configure cost models to accurately report costs

Now that you have configured your sources to collect cost and usage data into {product-title}, you can configure cost models to associate prices to metrics and usage, and fine-tune the costs of running your cloud.

A cost model is a framework used to define the calculations for the costs stored in {product-title}, using raw costs and metrics. Costs generated by a cost model can be recorded, categorized and distributed to specific customers, business units or projects.

From the {link-cost-models-app} area of {product-title}, you can:

* Classify your costs as infrastructure or supplementary costs
* Capture monthly costs for OpenShift nodes and clusters
* Apply a markup to account for additional support costs
* Learn how to configure a cost model in _{link-cost-models}_.




// Restore the context to what it was before this assembly.
ifdef::parent-context-of-assembly-cost-management-next-steps[:context: {parent-context-of-assembly-cost-management-next-steps}]
ifndef::parent-context-of-assembly-cost-management-next-steps[:!context:]
