[id="assembly_adding_ocp_sources"]
= Adding an OpenShift Container Platform source to cost management

This section describes how to connect your OpenShift Container Platform cluster to the cost management application.

To add an OpenShift Container Platform account to cost management, you must configure your OpenShift cluster to provide usage data (metrics) using the Cost Management Operator, then add the source in the cost management user interface. 

The Cost Management Operator collects the data required for cost management by:

* Using operator-metering to create cost and usage reports specific to cost management.
* Collecting and packaging these reports to a tarball which is uploaded to cost management through https://cloud.redhat.com/.

Begin adding your OpenShift Container Platform cluster as a source to cost management, then install and configure the Cost Management Operator from OperatorHub.

[NOTE]
====
An OpenShift Container Platform 4.3 or newer cluster is required to use the Cost Management Operator.
====

For your OpenShift Container Platform cluster to provide metrics to cost management:

. Install the Cost Management Operator in OpenShift
. Configure the Cost Management Operator to *DO WHAT*
. Provide the cluster identifier to cost management

As you will complete some of the following steps in OpenShift Container Platform, and some steps in the cloud.redhat.com platform (https://cloud.redhat.com/settings/sources/), have both applications open in a web browser, as well as a terminal to access the command line interface (CLI).



// include::../modules/installing_ocp_prerequisites.adoc[]


include::../modules/installing_cost_mgmt-operator.adoc[]


include::../modules/configuring_cost_mgmt-operator.adoc[]



//include::../modules/obtaining_metering_operator_login_ocp.adoc[]

//include::../modules/downloading_and_configuring_usage_collector_ocp.adoc[]

//include::../modules/uploading_data_with_usage_collector_ocp.adoc[]


Cost management will begin collecting cost and usage data from your OpenShift Container Platform cluster. The data can take a few days to populate before it shows on the cost management dashboard.

You have completed adding your OpenShift Container Platform cluster as a source.