[id="assembly_adding_ocp_sources"]
= Adding an OpenShift Container Platform 4.3 and 4.4 source to cost management

[NOTE]
====
Use these instructions with OpenShift Container Platform 4.3 or 4.4 for use with the `cost-mgmt-operator` operator. This operator is deprecated for OpenShift Container Platform 4.5 and later.

For OCP 4.5, see xref:assembly_koku_cost_management_installing[Adding sources to cost management for OpenShift Container Platform 4.5]
====

To add an OpenShift Container Platform cluster as a source to cost management, you must first configure your cluster to provide usage data (metrics) using the Cost Management Operator.

[NOTE]
====
You must have a Red Hat account user with Organization Administrator entitlements before you can add sources to cost management.
====

The Cost Management Operator (`cost-mgmt-operator`) collects the metrics required for cost management by:

* Using Operator Metering to create usage reports specific to cost management.
* Collecting and packaging these reports to a tarball which is uploaded to cost management through cloud.redhat.com.



To add your OpenShift Container Platform cluster as a cost management source:

. Install the Cost Management Operator in OpenShift from OperatorHub
. Configure the Cost Management Operator to collect OpenShift usage data (metrics) using Operator Metering
. Provide the cluster identifier to cost management

As you will complete some of the following steps in OpenShift Container Platform, and some steps in the cloud.redhat.com platform (https://cloud.redhat.com/settings/sources/), have both applications open in a web browser, as well as a terminal to access the command line interface (CLI).



include::../modules/installing_cost_mgmt-operator.adoc[]


include::../modules/configuring_cost_mgmt-operator.adoc[]



Cost management will begin collecting usage data (metrics) from your OpenShift Container Platform cluster. The data can take a few days to populate before it shows on the cost management dashboard.

You have completed adding your OpenShift Container Platform cluster as a source.
