// This assembly is included in the following assemblies:
//
// */getting_started/master.adoc

ifdef::context[:parent-context-of-assembly-adding-gcp-sources: {context}]

ifndef::context[]
[id="assembly-adding-gcp-sources"]
endif::[]
ifdef::context[]
[id="assembly-adding-gcp-sources_{context}"]
endif::[]

= Adding a Google Cloud source to {product-title}
:context: adding-gcp-sources

[role="_abstract"]
To add a Google Cloud account to {product-title}, you must configure your Google Cloud to provide metrics, then add your Google Cloud account as a source from the {platform} user interface.

[NOTE]
====
You must have a Red Hat account user with Sources Administrator entitlements before you can add sources to {product-title}.
====

[NOTE]
====
At this time, {openshift} resources running on Google Cloud Platform are not automatically associated in {product-title}. This feature will be available soon. 
====

Before you can add your Google Cloud account to {product-title} as a data source, you must configure the following services on your Google Cloud account to allow {product-title} access to metrics:

* Cost management Google Cloud project.
* Billing service account member with the correct role to export your data to {platform}.
* BigQuery dataset to contain the cost data.
* Billing export that sends the cost data to your BigQuery dataset.

As you will complete some of the following steps in the Google Cloud console, and some steps in the {product-title} user interface, keep both applications open in a web browser.

Add your Google Cloud source to {product-title} from the settings area at
https://cloud.redhat.com/settings/sources/.

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the link:https://cloud.google.com/docs[Google Cloud Platform documentation] for the most up-to-date and accurate information.
====

include::../modules/creating-a-project-gcp.adoc[leveloffset=+1]

include::../modules/creating-iam-role-gcp.adoc[leveloffset=+1]

include::../modules/adding-new-member-with-cost-role-gcp.adoc[leveloffset=+1]

include::../modules/creating-a-dataset-gcp.adoc[leveloffset=+1]

include::../modules/exporting-billing-data-gcp.adoc[leveloffset=+1]

include::../modules/viewing-data-collected-gcp.adoc[leveloffset=+2]

include::../modules/adding-a-gcp-account.adoc[leveloffset=+1]

////
Restore the context to what it was before this assembly.
////
ifdef::parent-context-of-assembly-adding-gcp-sources[:context: {parent-context-of-assembly-adding-gcp-sources}]
ifndef::parent-context-of-assembly-adding-gcp-sources[:!context:]
