[id="adding_an_aws_source"]
= Adding an Amazon Web Services (AWS) source to cost management


To add an AWS account to cost management, you must configure your AWS account to provide metrics, then add your AWS account as a source from the cost management user interface.

This creates a read-only connection to AWS in order to collect cost information hourly in cost management, but does not make any changes to the AWS account.

[IMPORTANT]
====
You must use an AWS master account for this procedure, as a linked AWS account does not have sufficient access to create billing accounts. After you add the master account as a source, cost management will collect data from any linked accounts as well.
====

Before you can add your AWS account to cost management as a data source, you must configure the following services on your AWS account to allow cost management access to metrics:

//ADD LINKS TO PROC TOPICS - this is a preview list//
. An S3 bucket to store cost and usage data reporting for cost management
. An Identity Access Management (IAM) policy and role for cost management to process the cost and usage data

As you will complete some of the following steps in the AWS console, and some steps in the cost management user interface, keep both applications open in a web browser.

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the https://docs.aws.amazon.com/[AWS documentation] for the most up-to-date and accurate information.
====

include::../modules/proc_creating_an_aws_s3_bucket.adoc[]

include::../modules/proc_activating_aws_tags.adoc[]

include::../modules/proc_enabling_aws_account_access.adoc[]

//include::../modules/proc_adding_an_aws_account.adoc[]
// this topic is covered in the other subsections.

You have completed adding your AWS account as a source.
