[id="adding_an_aws_source"]
= Adding an Amazon Web Services (AWS) Source to Cost Management

To use Cost Management to monitor your cloud costs, you must first connect a data source to the Cost Management application.

Currently, Cost Management can track costs for Amazon Web Services (AWS), Microsoft Azure, and Red Hat OpenShift Container Platform sources.


////
Adding a source
-> Adding an AWS source
----> Configuring your AWS account
-------> Create an S3 bucket
-------> Configure IAM
-------> Configure SNS notifications
----> Adding the AWS account to Cost Management
////


To add an AWS account to Cost Management, you must configure your AWS account to provide metrics, then add your AWS account as a source from the Cost Management user interface.

== Configuring your AWS account

//Should this section be its own assembly with the 3 topics? Then I could just link the last procedure with an include...)

Before you can add your AWS account to Cost Management as a data source, you must configure the following services on your AWS account to allow Cost Management access to metrics:

//ADD LINKS TO PROC TOPICS - this is a preview list//
. An S3 bucket to store cost and usage data reporting for Cost Management
. An Identity Access Management (IAM) policy and role for Cost Management to process the cost and usage data

include::modules/creating_an_aws_s3_bucket.adoc[]

include::modules/proc_enabling_aws_account_access.adoc[]

include::modules/proc_adding_an_aws_account.adoc[]

You have completed adding your AWS account as a source.
