// This assembly is included in the following assemblies:
//
// master.adoc

ifdef::context[:parent-context: {context}]

[id="assembly_cost_management_next_steps"]
// If the assembly is reused in other assemblies in a guide, include {context} in the ID: [id="a-collection-of-modules_{context}"].
= Next steps for managing your costs
:context: assembly-keyword
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.

After adding your infrastructure and cloud sources, in addition to showing cost data by source, cost management will automatically show AWS and Azure cost and usage related to running your OpenShift Container Platform clusters on AWS or Azure. 

On the cost management *Overview* page, use the *Perspective* options for different views of your cost data.

Use the *Details* menu to look more closely at your costs.

== Configure tagging for your sources

The cost management application tracks cloud and infrastructure costs using tags (called labels in OpenShift), which you can refine to filter and attribute to resources. Tags in cost management allow you to organize your resources by cost and to allocate the costs to different parts of your cloud infrastructure.

[IMPORTANT]
====
Tags and labels can only be configured directly on a source. You cannot edit tags and labels in the cost management application.
====

See https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html-single/managing_cost_data_using_tagging/index[_Managing cost data using tagging_] to learn more about: 

* Planning your tagging strategy to organize your view of cost data
* Understanding how cost management associates tags
* Configuring tags and labels on your sources



== Configure cost models to accurately report costs

Now that you have configured your sources to collect cost and usage data into cost management, you can configure cost models to associate prices to metrics and usage, and fine-tune the costs of running your cloud.

A cost model is a framework used to define the calculations for the costs stored in cost management, using raw costs and metrics. Costs generated by a cost model can be recorded, categorized and distributed to specific customers, business units or projects.

From the https://cloud.redhat.com/cost-management/cost-models[Cost models] area of cost management, you can:

* Classify your costs as infrastructure or supplementary costs
* Capture monthly costs for OpenShift nodes and clusters
* Apply a markup to account for additional support costs
* Learn how to configure a cost model in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html-single/using_cost_models/index[_Using cost models_]. 




// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
//
