[id="adding_an_azure_source"]
= Adding a Microsoft Azure source to cost management


////
Structure:
Adding a source
-> Adding an Azure source
-------> Creating a storage account
-------> Creating a service principal
-------> Configure a daily Azure data export schedule
////


This section describes how to configure your Microsoft Azure account to allow cost management access. 

Configuring your Azure account to be a cost management source requires:

. Creating a storage account and resource group
. Configuring a Storage Account Contributor and Reader roles for access
. Scheduling daily cost exports

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the https://docs.microsoft.com/en-us/azure/[Microsoft Azure documentation] for the most up-to-date and accurate information.
====

Add your Azure source to cost management from 
https://cloud.redhat.com/settings/sources/.


include::../modules/creating_an_azure_storage_account.adoc[]

include::../modules/configuring_azure_roles.adoc[]

include::../modules/configuring_an_azure_daily_export_schedule.adoc[]

You have completed adding your Azure account as a source.
