[id="assembly_adding_ocp_sources"]
= Adding an OpenShift Container Platform source to cost management

This section describes how to connect your OpenShift Container Platform cluster to the cost management application.

To add an OpenShift Container Platform account to cost management, you must configure your OpenShift cluster to provide Operator Metering usage data (metrics), then add the source in the cost management user interface. 

For your OpenShift Container Platform cluster to provide metrics to cost management:

. Install and configure the prerequisites.
. Obtain a login token for your reporting-operator service account.
. Download and configure the Usage Collector Ansible playbook to generate report resources for your OpenShift cluster.
. Create a cron job to regularly collect and send Operator Metering usage data to the upload service.

As you will complete some of the following steps in OpenShift Container Platform, and some steps in the cloud.redhat.com platform (https://cloud.redhat.com/beta/settings/sources/), have both applications open in a web browser, as well as a terminal to access the command line interface (CLI).


.Prerequisites
//What kind of module does this go into? Reference? In the procedure?
// Add links to other docs that show you how to install these.

To obtain the OpenShift Operator Metering usage data, cost management requires the following:

*On your OpenShift cluster*

* OpenShift Container Platform 4.3
* Operator Metering
+
Operator Metering is not deployed out of the box in OpenShift Container Platform. See https://docs.openshift.com/container-platform/4.3/metering/metering-installing-metering.html[Installing Metering] in the OpenShift documentation for instructions to install metering from OperatorHub.

// TODO: * Update to OCP 4.3 throughout, links and refs

*On a Red Hat Enterprise Linux (RHEL) system with network access to your OpenShift cluster*

* Red Hat Insights client - installed and registered:
+
. Register your RHEL system with Red Hat Subscription Manager and automatically attach subscriptions:
+
----
# subscription-manager register  --auto-attach
----
+
. Install the Insights client if using a RHEL 7 system:
+
----
# yum install -y insights-client
----
+
[NOTE]
====
The Insights client is installed by default on Red Hat Enterprise Linux 8.
====
+
Register the system to Red Hat Insights:
+
----
# insights-client --register
----
+
. Open the `insights-client.conf` config file, and change the authentication method to `BASIC` and provide the credentials for your Red Hat account. To do this, edit the following lines:
** Uncomment the line `authmethod=BASIC`
** Uncomment and add your Red Hat login username as `username=<yourRedHatlogin>`
** Uncomment and add the password for your Red Hat login as `password=<password>`
+
----
# sudo vi /etc/insights-client/insights-client.conf
----
+
Save your changes to the file.
+
[NOTE]
====
See https://access.redhat.com/products/red-hat-insights/#getstarted[Get Started with Red Hat Insights] for more information.
====
* Ansible (included in the RHEL “extras” repository): 
https://access.redhat.com/articles/3174981
+
See https://access.redhat.com/articles/3174981[How do I Download and Install Red Hat Ansible Engine?] for more information.
+
* OpenShift command line tools (oc)
+ 
See https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli_cli-developer-commands[Installing the CLI] in the _OpenShift documentation_.


include::../modules/obtaining_metering_operator_login_ocp.adoc[]

include::../modules/downloading_and_configuring_usage_collector_ocp.adoc[]

include::../modules/uploading_data_with_usage_collector_ocp.adoc[]


Cost management will begin collecting cost and usage data from your OpenShift Container Platform cluster. The data can take a few days to populate before it shows on the cost management dashboard.

You have completed adding your OpenShift Container Platform cluster as a source.