[id="adding_an_aws_source"]
= Adding an Amazon Web Services (AWS) Source to cost management


To add an AWS account to cost management, you must configure your AWS account to provide metrics, then add your AWS account as a source from the cost management user interface.

== Configuring your AWS account

//Should this section be its own assembly with the 3 topics? Then I could just link the last procedure with an include...)

Before you can add your AWS account to cost management as a data source, you must configure the following services on your AWS account to allow cost management access to metrics:

//ADD LINKS TO PROC TOPICS - this is a preview list//
. An S3 bucket to store cost and usage data reporting for cost management
. An Identity Access Management (IAM) policy and role for cost management to process the cost and usage data

include::../modules/proc_creating_an_aws_s3_bucket.adoc[]

include::../modules/proc_enabling_aws_account_access.adoc[]

include::../modules/proc_adding_an_aws_account.adoc[]

You have completed adding your AWS account as a source.
