[id="assembly_restricting_user_access"]
= Restricting User Access to Cost Data

////
WIP structure
- intro
- prerequisites (admin access, which users) (is prereqs a concept module?)
- procedures - user, role, group, etc
- ref - what the user roles mean
////

In certain cases, you may not want users to have access to all cost data, but instead only data specific to their projects or organization. Using role-based access control, you can limit the visibility of resources involved in cost management reports.

Role-based access control works by organizing users into groups, which can be associated with one or more policies. A policy associates a group with a set of roles. A role defines a permission and a set of resource definitions.

By default, a user who is not an account administrator will not have access to data, but instead must be granted access to resources. Account administrators can view all data without any further role-based access control configuration.


include::modules/configuring_user_access.adoc[]

== Configuring user access to AWS data

Reports for Amazon Web Services (AWS) sources can be scoped by usage account or its account alias. For example, if an administrator has eight Amazon accounts specific to different organizations within the company, but only wants to allow a user to see the data associated with their organization  or account, you can limit their access to filter the data for that specific AWS account.

To configure this:

. Create a group that includes the users for that organization.
. Define a role can be that allows “read” permission on the specified Amazon account.
. Create a policy that associates the group and role.

Now any user in that group will have visibility limited to just that Amazon account.

== Configuring user access to Openshift Container Platform data

Reports for OpenShift Container Platform sources can be scoped by the cluster, node, and project. To see report data, users must have visibility to a cluster. Visibility can be further limited by specifying nodes or projects. For example, an administrator might have two clusters configured (one for pre-production and one for production) and wants to expose the cost of projects deployed on these clusters to the associated development teams.

To configure this:

. Create a group for each development team.
. Define roles to grant “read” access to each of the clusters but only the specific project.
. Create a policy to associate a specific group with the role that provides them visibility to only their project.

Reports involving OpenShift Container Platform running on Amazon Web Services require visibility to be set up on both the Amazon account and the OpenShift Container Platform resources as described above.


//What kind of access is required to configure access management? Any other prerequisites?

include::modules/con_access_management.adoc[]
