[id="adding_an_azure_source"]
= Adding a Microsoft Azure source to cost management


////
Adding a source
-> Adding an Azure source
-------> Creating a storage account
-------> Creating a service principal
-------> Configure a daily Azure data export schedule
////


This section describes how to configure your Microsoft Azure account to allow cost management access. 

Configuring your Azure account to be a cost management source requires:
* Creating a storage account and resource group
* Setting up an application and service principal for access
* Scheduling daily cost exports

[NOTE]
====
As non-Red Hat products and documentation can change without notice, instructions for configuring the third-party sources provided in this guide are general and correct at the time of publishing. See the Microsoft Azure documentation for the most up-to-date and accurate information.
====


include::../modules/creating_a_storage_account_azure.adoc[]

include::../modules/creating_a_service_principal_azure.adoc[]

include::../modules/configuring_a_daily_export_schedule_azure.adoc[]

You have completed adding your Azure account as a source.
