// Module included in the following assemblies:
// assembly_Adding_OCP_sources.adoc
[id="proc_Adding_an_OCP_cluster"]
== Adding your OpenShift Container Platform cluster as a source

// The URL for this procedure needs to go in the UI code in the Sources dialog - need to give to Dan & Boaz.

Using the information from the previous steps, you can now add your OpenShift Container Platform cluster as a source. After adding an OpenShift source, the cost and usage data from your OpenShift Container Platform cluster will be processed and made viewable within the Cost Management application.

. In Cost Management, click *Add source* to open the dialog.
. In the dialog, select *OpenShift Container Platform* as the source type.
. Enter a name for the source and click *Next*.
//edit from here.
. Paste your cluster identifier and click *Next*.
. Confirm the source details and click *Add source*.

Cost Management will begin collecting cost and usage data from your OpenShift Container Platform cluster. This can take a few days to populate to show on your dashboard.



