// Module included in the following assemblies:
// assembly_Adding_OCP_sources.adoc
[id="proc_Uploading_data_with_Usage_Collector"]
=== Uploading data with usage collector

// The URL for this procedure needs to go in the UI code in the Sources dialog - need to give to Dan & Boaz.

The Usage Collector retrieves usage data from the Operator Metering endpoint and compresses it into a package that is uploaded for processing by Cost Management via the Red Hat Insights Client. Collection of data is performed via the _ocp_usage.sh_ script.

Create a cron job to regularly upload data collected by the Usage Collector to Cost Management.

[IMPORTANT]
====
The cron user requires:
* access to the file with metering-operator token 
* sudo access to interact with the Red Hat Insights client.
==== 

. To configure sudo access, add the following to the _/etc/sudoers_ file, substituting _ocpcollector_  with the cron user:
+
----
ocpcollector    ALL=(ALL)    NOPASSWD: ALL
----
+
. Open the crontab for the user that will execute this scheduled upload:
+
----
# crontab -u <username> -e
----
+
. Create a crontab entry to run the Usage Collector every 45 minutes:
+
----
 */45 * * * * /path/to/ocp_usage.sh --collect
----







. Download the Usage Collector on the same system where the Red Hat Insights Client was installed.
. Navigate to the korekuta-master directory to find the ocp_usage.sh script. 
. Run the ocp_usage.sh script to set up the Usage Collector. 
+
Use the following example, substituting values for your OpenShift API endpoint, Operator Metering namespace, and metering-operator token file path:
+
----
# ./ocp_usage.sh --setup -e OCP_API="https://api.openshift-prod.mycompany.com"  -e OCP_METERING_NAMESPACE="metering" -e OCP_TOKEN_PATH="/path/to/ocp_usage_token"
----
+
[NOTE]
====
If the oc command line is installed in a different location from /usr/bin/oc on your system, specify the path using -e OCP_CLI=</path/to/oc> when executing the ocp_usage.sh command.
+
You will be prompted for your sudo password and the Ansible playbook will execute to capture the configuration information and create the usage reports on your OCP cluster. When complete you will see the following message:
+
----
TASK [setup : Display New Cluster Identifier] **********************************
ok: [localhost] => {
    "msg": "Use the following value, <YOUR_OCP_IDENTIFIER>, for the cluster identifier when configuring an OCP provider in Cost Management."
}
----
====
+
. Record the cluster identifier and enter it into the field in the user interface. 
+
[NOTE]
====
The cluster identifier value is also stored in ~/.config/ocp_usage/config.json.
====

