// Module included in the following assemblies:
// assembly_Adding_AWS_sources.adoc
[id="proc_Enabling_account_access_IAM"]
= Enabling account access for cost and usage consumption 

// The URL for this procedure needs to go in the UI code in the Sources dialog - need to give to Dan & Boaz.

To provide data within the web interface and API, Cost Management needs to consume the Cost and Usage reports produced by AWS. For Cost Management to obtain this data with the minimal amount of access, create an IAM policy and role for Cost Management to use.

Configure the following from the AWS Identity Access Management (IAM) console:

. Create a new IAM policy for the S3 bucket you configured in Configuring an Amazon Account for Cost & Usage Reporting. 
. Paste the following content in the JSON policy text box and name the policy _CostUsage_:
+
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket_name",
                "arn:aws:s3:::bucket_name/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "iam:ListAccountAliases",
                "s3:HeadBucket",
                "cur:DescribeReportDefinitions"
            ],
            "Resource": "*"
        }
    ]
}
----
+
[NOTE]
====
Including Action *iam:ListAccountAliases* allows Cost Management to display the AWS account alias rather than the account ID.
====
+ 
. Create a new IAM role with the following values:
+
----
Trusted entity: Another AWS Account
Account ID: 589173575009
Permissions: CostUsage (the IAM policy created in <xref>)
Name: CostManagement
----
+
[IMPORTANT]
====
Note the Role ARN to be used later when adding AWS as a source.
====





