Getting started with cost management

:context: getting_started

[INTRO]
C Introduction to cost management
C About cost management
C Terminology
C Planning

[RBAC]
Limiting access to cost management resources
P Adding a role
P Adding a role to a group

[ADDING SOURCES]
Adding sources
A Adding an Amazon Web Services (AWS) source	
P -- Creating an S3 bucket for reporting
P -- Activating tags for cost management 	
P -- Enabling account access for cost and usage consumption

A Adding a Microsoft Azure source	
P -- Creating a storage account	
P -- Creating a service principal	
P -- Configuring a daily Azure data export schedule	

A - Adding an OpenShift Container Platform source
-- Prerequisites
P -- Obtaining Metering Operator login credentials	
P -- Downloading and configuring the Usage Collector
P -- Uploading data with Usage Collector

[CONFIGURING TAGGING]
A Organizing cost data using tags
C How cost management associates tags between sources
C Adding a tag to an AWS resource	
C Adding a tag to an Azure resource	
C Adding a label to an OpenShift namespace	


-----

Using cost models

:context: cost_models

- Introduction
A -- Document Scope       in assembly

- How cost management uses cost models
C - What is a cost model? 
R -- Terminology 
C - The cost model workflow 

- Assigning a cost to metrics and usage using a cost model 
P -- Creating an AWS cost model 
P -- Creating an OpenShift Container Platform cost model 

-----

Exporting cost data using the API


:context: exporting_api

A - Introduction
C - How the data export API works
P - Exporting cost data to an AWS bucket
P - Viewing previous data export requests
R - Data export API parameters


------

Managing cost data using tagging

:context: tagging

MAP
C  How cost management associates tags between sources
 --> Tag matching hierarchy
C Designing your tagging strategy
(P  Tagging in a multi-cluster environment)
R Tag specifications by source type	
Additional resources



