[id='Adding_an_OpenShift_source']
= Adding an OpenShift Container Platform source to Cost Management

To monitor and track your cloud costs using Cost Management, you must first connect a data source to Cost Management.

Currently, you can use Cost Management to manage costs for OpenShift Container Platform and Red Hat OpenShift Container Platform sources.

This section describes how to configure your OpenShift Container Platform cluster to provide Cost Management operator metering usage data. 

////
Adding a source
-> Adding an OpenShift source
----> Configuring your OpenShift cluster
-------> Create an S3 bucket
-------> Configure IAM
-------> Configure SNS notifications
----> Adding the OpenShift cluster to Cost Management
////


To add an OpenShift Container Platform account to Cost Management, you must configure your OpenShift cluster, then add the source in the Cost Management user interface.

== Configuring your OpenShift Container Platform cluster

//Should this section be its own assembly with the 3 topics? Then I could just link the last procedure with an include...)

Before you can add your OpenShift cluster to Cost Management for monitoring, you must configure your OpenShift Container Platform account to allow Cost Management access to metrics. 


=== Prerequisites
//What kind of module does this go into?
// Add links to other docs that show you how to install these.

To obtain the OpenShift operator metering usage data, Cost Management requires the following prerequisites installed:

On your OpenShift cluster
* OpenShift Container Platform 3.11 or newer
* Operator Metering

On a system with network access to your OpenShift cluster
* Red Hat Insights Client
* Ansible and EPEL repositories
* OpenShift command line tools (oc)

Configuring your account involves configuring the following OpenShift Container Platform services:

//ADD LINKS TO PROC TOPICS - this is a preview list//
. Obtaining a login token for your metering-operator service account. 
. Downloading and configuring the Usage Collector Ansible playbook to generate report resources for your OpenShift cluster. 
. Creating a cron job to regularly collect and send operator metering usage data to the upload service. 


include::proc_Obtaining_Operator_Metering_login.adoc[]
include::proc_Downloading_and_Configuring_Usage_Collector[]
include::proc_Uploading_Data_with_Usage_Collector.adoc[]



// This probably needs the title here - 'Adding your OpenShift Container Platform account as a source', but I've put the title in the proc topic. Where should it go?
// Adding an OpenShift Container Platform cluster as a source

include::proc_Adding_an_OCP_cluster.adoc[]

You have completed adding your OpenShift Container Platform account as a source.

