[id='Adding_an_AWS_source']
= Adding an Amazon Web Services (AWS) source to Cost Management

To monitor and track your cloud costs using Cost Management, you must first connect a data source to Cost Management.

Currently, you can use Cost Management to manage costs for Amazon Web Services (AWS) and Red Hat OpenShift Container Platform sources.

This section describes how to configure your AWS account to provide Cost Management operator metering usage data. 

////
Adding a source
-> Adding an AWS source
----> Configuring your AWS account
-------> Create an S3 bucket
-------> Configure IAM
-------> Configure SNS notifications
----> Adding the AWS account to Cost Management
////


To add an AWS account to Cost Management, you must configure your AWS account to provide metrics, then add your AWS account as a source from the Cost Management user interface.

== Configuring your AWS account

//Should this section be its own assembly with the 3 topics? Then I could just link the last procedure with an include...)

Before you can add your AWS account to Cost Management for monitoring, you must configure the following services on your AWS account to allow Cost Management access to metrics:

//ADD LINKS TO PROC TOPICS - this is a preview list//
. An S3 bucket to store cost and usage data reporting for Cost Management
. An Identity Access Management (IAM) policy and role for Cost Management to process the cost and usage data
. (Optional) An AWS simple notification service (SNS) to trigger processing of cost and usage data when created or updated


include::proc_Creating_an_S3_bucket.adoc[]
include::proc_Enabling_AWS_account_access.adoc[]
include::proc_Enabling_SNS_notifications.adoc[]



// This probably needs the title here - 'Adding your AWS account as a source', but I've put the title in the proc topic. Where should it go?
// Adding an AWS account as a source

include::proc_Adding_an_AWS_account.adoc[]

You have completed adding your AWS account as a source.

